### ISSUE TITLE
I hope to develop a plug-in system as soon as possible

### ISSUE THREAD

**Issue by QCEEE** [RSSNext/Follow#1870] opened 2024-11-26 16:11 UTC
### Clear and concise description of the problem

There are many problems in the compatibility of the display of various types of articles and media in the software, which can be solved by the open plug-in system

### Suggested solution

I hope that the plugin system can be opened up for further use in the future to meet the needs of more users, such as my need to separate video, pictures, and text content on social media, rather than having text content reported as an error in the picture category to affect the viewing experience, video content not being able to correctly identify its size, resulting in poor preview effects in the picture category, and not being able to correctly display subscription content for Telegram content. I also think that the ability to properly display content from various platforms can be improved by opening up the plugin system. This can also reduce the development cycle and difficulty of the software, as the development capabilities of a single studio are limited.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by TonyRL** [comment] 2024-11-26 16:30
Duplicate of #26

**Closed** 2024-11-27 02:39 UTC
Labels: enhancement
