### ISSUE TITLE
render math formula in LaTeX via MathJaX or KaTeX

### ISSUE THREAD

**Issue by jasonVSCode** [RSSNext/Follow#2032] opened 2024-12-06 14:39 UTC
### Clear and concise description of the problem

RSS subscriptions of arxiv.org/rss/math or https://zbmath.org/atom/cc/ do not render math formula correctly. 
arxiv.org/rss uses $ $ for math formula
zhmath.org/atom/cc/ uses \( \) for math formula

### Suggested solution

Invoke https://www.mathjax.org/ for math formula.
It would be better to have a local installation.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by TonyRL** [comment] 2024-12-06 14:48
Duplicate of #917

**Comment by hyoban** [comment] 2024-12-11 08:10
We cannot treat `$ $` in plain text as a math formula. The feed itself needs to output math nodes like https://dreams.plus/blog/2024-09-18-the-stirling-formula

**Closed by hyoban** 2024-12-11 08:10 UTC
Labels: enhancement
