### ISSUE TITLE
Some users on Twitter cannot follow it

### ISSUE THREAD

**Issue by Amour2077** [RSSNext/Follow#1045] opened 2024-10-21 09:47 UTC
### Describe the bug

尝试在follow上订阅了7个推特用户，只成功了三个。web版和Windows应用程序的表现相同。
![屏幕截图 2024-10-21 173707](https://github.com/user-attachments/assets/4072748b-28aa-4702-8e33-87f0d301b969)

### Feed Info

YouwoLin https://x.com/YouwoLin

### App Type

Web

### Operating System

Windows 11

### Browser Info

chrome 

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-21 11:28
Duplicate of #740

**Closed by hyoban** 2024-10-21 11:28 UTC
