### ISSUE TITLE
Error in fetching feed: rsshub://xiaohongshu/user/5930ca015e87e74f97e036ed/notes

### ISSUE THREAD

**Issue by wulihua222** [RSSNext/Follow#1664] opened 2024-11-19 09:57 UTC
### Info:

Feed URL:
```
rsshub://xiaohongshu/user/5930ca015e87e74f97e036ed/notes
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/xiaohongshu/user/5930ca015e87e74f97e036ed/notes?format=json": 500 Internal Server Error
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
**Env**: web
**Browser**: Microsoft Edge
**Session Trace Id**: `wvrxevW6hNIR8Tk5bZA5s`

**Comment by hyoban** [comment] 2024-11-19 10:22
Duplicate of #1662

**Closed by hyoban** 2024-11-19 10:22 UTC
