### ISSUE TITLE
Error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by lizhong0829** [RSSNext/Follow#1278] opened 2024-11-01 06:34 UTC
### Error

Cannot convert undefined or null to object

### Stack

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/recommendations-D1k6suzr.js:1:4702
    at Array.sort (<anonymous>)
    at file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/recommendations-D1k6suzr.js:1:4638
    at Object.useMemo (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/main-D0gxHiwl.js:71:26036)
    at react_production_min.useMemo (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/main-D0gxHiwl.js:10:7277)
    at Z (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/recommendations-D1k6suzr.js:1:4609)
    at Nh (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/main-D0gxHiwl.js:71:19019)
    at Vk (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/main-D0gxHiwl.js:73:48765)
    at Uk (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/main-D0gxHiwl.js:73:43991)
    at Tk (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/main-D0gxHiwl.js:73:43912)
    at Ik (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/main-D0gxHiwl.js:73:43752)
    at Nk (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/main-D0gxHiwl.js:73:39720)
    at Gk (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/main-D0gxHiwl.js:73:38544)
    at dn (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/main-D0gxHiwl.js:58:1729)
    at MessagePort.Sn (file:///C:/Users/17111/AppData/Local/Follow/app-0.1.1-beta1/resources/app.asar/dist/renderer/assets/main-D0gxHiwl.js:58:2141)
```

### Environment

**App Version**: 0.1.1-beta.1
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.1-beta.1 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment] 2024-11-01 07:27
Duplicate of #1273

**Closed** 2024-11-02 04:14 UTC
