### ISSUE TITLE
订阅源鼠标拖动至指定文件夹的功能

### ISSUE THREAD

**Issue by neonjourney** [RSSNext/Follow#549] opened 2024-09-22 04:00 UTC
### Clear and concise description of the problem

能否添加个订阅源鼠标拖动至指定文件夹的功能，这样整理源更方便些 谢谢

### Suggested solution

能否添加个订阅源鼠标拖动至指定文件夹的功能，这样整理源更方便些 谢谢

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment] 2024-10-28 13:45
Duplicate of #1193

**Closed by TonyRL** 2024-10-28 13:45 UTC
Labels: enhancement
