### ISSUE TITLE
Subscription limit exceeded

### ISSUE THREAD

**Issue by milan-chen** [RSSNext/Follow#930] opened 2024-10-14 05:39 UTC
### Clear and concise description of the problem

When I make a new subscription, it says Subscription limit exceeded. Will the quantity be expanded in the future?

### Suggested solution

11

### Validations

- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment] 2024-10-28 13:49
Duplicate of #1164

**Comment by hyoban** [comment] 2024-10-28 14:36
We already have plans to allow users to expand the number of subscriptions they can create, but for now, you can't create more than 500 subscriptions

**Closed by hyoban** 2024-10-28 14:36 UTC
Labels: enhancement
