### ISSUE TITLE
Drag to set/change category

### ISSUE THREAD

**Issue by Erica-Iris** [RSSNext/Follow#477] opened 2024-09-18 11:47 UTC
### Clear and concise description of the problem

I'd like to be able to drag a subscription item directly into an existing category to set the subscription directly to that category. Or drag a subscription out of a category to cancel the existing category setting. Instead of right clicking on the subscription and then clicking edit to remove the current category from the category.

### Suggested solution

Add drag function to subscription item.

### Additional context

Like this

<img width="317" alt="image" src="https://github.com/user-attachments/assets/fd593db8-c2c0-43e3-9433-8bb8afb1e1d4">

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment] 2024-10-28 13:47
Duplicate of #1193

**Closed** 2024-10-28 14:32 UTC
Labels: enhancement, ux
