### ISSUE TITLE
图片区无法加载

### ISSUE THREAD

**Issue by PapainTea** [RSSNext/Follow#739] opened 2024-10-01 16:04 UTC
### Describe the bug

我用图片区订阅了一些 tg 频道的网盘影视资源，但好像只能显示今天的内容
![B969C70D3AF06D61797C8AC0F8CB0D18](https://github.com/user-attachments/assets/5b15c69b-1c40-4195-abf8-ba771d60326a)

### Feed Info

rsshub://telegram/channel/shareAliyun
rsshub://telegram/channel/Aliyun_4K_Movies
rsshub://telegram/channel/Q66Share
rsshub://telegram/channel/alyp_Animation

### App Type

Electron / App

### Version

0.0.1-alpha

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-10-01 16:59
Duplicate of #647

**Closed** 2024-10-18 03:43 UTC

**Comment by hyoban** [comment] 2024-10-18 03:49
We have temporarily turned off the feature of updating the pulled entry content, so the image link has expired.
