### ISSUE TITLE
The button in the upper left corner of the text cannot be closed or goback

### ISSUE THREAD

**Issue by alucardzlh** [RSSNext/Follow#1449] opened 2024-11-07 01:46 UTC
### Describe the bug

步骤：
1、启动follow
2、随便点击文章或社交等 正文页面
3、进入正文后点击左上角 X按钮 无法回退上一页，或关闭正文

       

### Feed Info

环境：
Follow mac端
mac os Sequoia 15.1
macbook M1 Pro
![Image](https://github.com/user-attachments/assets/32bf45f5-8dcf-486a-8756-d967d06dca20)

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by ucasey** [comment] 2024-11-07 03:14
I have the same problem

**Comment by TonyRL** [comment] 2024-11-07 03:16
Duplicate of #1311

**Closed** 2024-11-08 03:13 UTC
