### ISSUE TITLE
v0.2.0-beta.0 Sidebar bug

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1512] opened 2024-11-08 17:16 UTC
### Describe the bug

1. I selected a single feed and tried to drag it, but I couldn't. It entered multi-select mode, and the triggers for multi-select and dragging are unclear.

https://github.com/user-attachments/assets/a48500b8-7a50-48a8-bc87-17631c8e5e0a

2. These two sorting methods cause issues when using multi-select.
![Image](https://github.com/user-attachments/assets/ab3860c8-abab-4d99-ba25-e6876bc882ac)

https://github.com/user-attachments/assets/b2b2b40d-80d1-4957-b765-c9bf7f829acd

3. Once you've multi-selected, you can't click on a selected item to deselect it.

https://github.com/user-attachments/assets/214d5b41-c15f-4339-bb5f-5362313ed884

4. I am unable to view the content at the bottom, unless I enlarge the window.

https://github.com/user-attachments/assets/7da51260-0396-42e7-a85b-18164a188dfc

### Feed Info

X

### Environment

**App Version**: 0.2.0-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `7tZLayeRkRaLl7Nrv3Ts4`

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment] 2024-11-09 08:32
@hyoban take a look this

**Comment by hyoban** [comment] 2024-11-11 02:44
- 4 fixed in https://github.com/RSSNext/Follow/pull/1528

Can you reproduce 2 now?

**Comment by EnterMan123** [comment] 2024-11-11 03:48
5.

https://github.com/user-attachments/assets/fc98ec08-d5cc-431a-a0c1-3836b4eb236c

**Comment by hyoban** [comment] 2024-11-11 04:01
I cannot reproduce 2, please provide a complete screen recording of the reproduction process. 6 has been fixed in the latest dev.

**Comment by EnterMan123** [comment] 2024-11-11 04:03
https://github.com/user-attachments/assets/3b11df51-37d7-4ca5-8863-7d6c1a5aa1e4

![Image](https://github.com/user-attachments/assets/16e50511-df11-400c-a2a2-a2a003fce955)

Please be mindful of the selection sorting method.

**Comment by hyoban** [comment] 2024-11-11 04:04
I got it, you changed the sorting method during the feed selection process, which will cause problems

**Comment by hyoban** [comment] 2024-11-11 04:13
I may have made a mistake. Is the flashing feed related to the fact that they are set to private?

**Comment by EnterMan123** [comment] 2024-11-11 04:18
https://github.com/user-attachments/assets/f21d0196-2ee7-4daa-8d33-e25851e958fa


I don't think that's the case. Even if I click randomly, the order changes, so it seems to be an issue with the sorting method.

**Comment by EnterMan123** [comment] 2024-11-11 04:19
I have turned off all the private feed settings.

**Comment by hyoban** [comment] 2024-11-11 04:22
So this doesn't seem to be related to dnd, can you open a new issue and link to the discussion here?

**Comment by hyoban** [comment] 2024-11-11 04:24
5 fixed in https://github.com/RSSNext/Follow/commit/8666b41f2dded5b6b5cb86b7824683b48582cf1d

**Comment by EnterMan123** [comment] 2024-11-11 04:54
I added it randomly through the follow search feature.

**Comment by hyoban** [comment] 2024-11-11 13:44
I have reproduced problem 2 on the web page of the current production environment, but it has not been reproduced on the latest dev branch. Can you help me try the latest version?

https://github.com/RSSNext/Follow/actions/runs/11774868921

**Comment by EnterMan123** [comment] 2024-11-11 14:14
https://github.com/user-attachments/assets/5593c0b6-17bb-4b84-aada-7fc0bb5eaed1

**Comment by hyoban** [comment] 2024-11-11 14:19
Are you holding the command key while dragging?

**Comment by EnterMan123** [comment] 2024-11-11 14:20
left mouse button only

**Comment by EnterMan123** [comment] 2024-11-11 14:24
https://github.com/user-attachments/assets/b38f58e1-8082-4c41-8a38-f4f1b7a3a8e6

**Comment by EnterMan123** [comment] 2024-11-11 14:29
https://github.com/user-attachments/assets/9ea3528c-5b93-4b45-9dd5-c1dbc0e80610

**Comment by hyoban** [comment] 2024-11-11 14:38
Can you contact me at https://t.me/hyoban? I may need more information to debug this issue

**Comment by EnterMan123** [comment] 2024-11-16 09:19
https://github.com/user-attachments/assets/493f2632-4e84-482e-8a06-344415f023b6

Latest Test: Disabling auto-grouping in version **0.2.1-nightly.20241115** seems to improve the situation.

**Comment by hyoban** [comment] 2024-11-18 06:16
Can you help me try this version? https://github.com/RSSNext/Follow/actions/runs/11886777612

**Comment by EnterMan123** [comment] 2024-11-18 09:59
Tested on version 0.2.2-beta.0, and I believe this issue has been resolved. However, there is still a 1% chance of sorting errors, though it works correctly 99% of the time.

**Comment by hyoban** [comment] 2024-11-18 10:01
Glad to hear this, if you have more questions feel free to create a new issue

**Closed by hyoban** 2024-11-18 10:01 UTC
