### ISSUE TITLE
Can't watch YouTube videos?

### ISSUE THREAD

**Issue by Eroticoo** [RSSNext/Follow#1778] opened 2024-11-24 06:17 UTC
### Describe the bug

![Image](https://github.com/user-attachments/assets/901dcb94-7027-407d-aeb5-e4b4a2f20d6e)
如图，我选择登陆，但是系统提示说登录不成功，这个浏览器未取得信任，应该如何解决呢？

### Feed Info

ID Estrella 

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-11-25 07:45
Duplicate of #1451

**Closed by hyoban** 2024-11-25 07:45 UTC
