### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by jinhwg** [RSSNext/Follow#1231] opened 2024-10-30 01:31 UTC
### Clear and concise description of the problem

can not search a topic? 

### Suggested solution

please add this function 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment] 2024-10-30 01:34
Duplicate of #927

**Closed** 2024-10-30 01:55 UTC
Labels: enhancement
