### ISSUE TITLE
Error in fetching feed: rsshub://picnob/user/Andhika%20Ramadhian

### ISSUE THREAD

**Issue by GangGangGangGangGangGangGang** [RSSNext/Follow#1452] opened 2024-11-07 02:55 UTC
### Info:

Feed URL:
```
rsshub://picnob/user/Andhika%20Ramadhian
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/picnob/user/Andhika%20Ramadhian?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment] 2024-11-08 10:43
Duplicate of #1329

**Closed by hyoban** 2024-11-08 10:43 UTC
