### ISSUE TITLE
Suggest providing item filter function

### ISSUE THREAD

**Issue by ikelvingo** [RSSNext/Follow#2261] opened 2024-12-19 16:04 UTC
### Environment

**App Version**: 0.2.7-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.7-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `KcSaDXnaNngu6jaocUgrv`

Suggest FOLLOW could provide item content filter function, just like inoreader's feed filter.

![Image](https://github.com/user-attachments/assets/1deff5ff-634e-4763-a890-76dab60d73cd)

**Comment by TonyRL** [comment] 2024-12-19 17:05
Duplicate of #1031

**Closed** 2024-12-26 03:52 UTC
