### ISSUE TITLE
Error in fetching feed: rsshub://twitter/user/FIFI_Egypt

### ISSUE THREAD

**Issue by 593388896** [RSSNext/Follow#1630] opened 2024-11-16 15:44 UTC
### Info:

Feed URL:
```
rsshub://twitter/user/FIFI_Egypt
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/FIFI_Egypt?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.1-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.1-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `ELffTCYEQfkMCJCfkp2Wq`

**Comment by TonyRL** [comment] 2024-11-16 15:53
Duplicate of #740

**Closed** 2024-11-16 15:54 UTC
