### ISSUE TITLE
The upper limit of subscription number hopes to be enlarged

### ISSUE THREAD

**Issue by lxyer** [RSSNext/Follow#2377] opened 2024-12-30 03:01 UTC
### Clear and concise description of the problem

订阅了很多人的博客，几个月发一篇，其实RSS订阅数据不大，咱们现在500的订阅上限感觉非常不够用。

### Suggested solution

数据同步保存到用户本地，不占用Follow服务器的太多空间，opml文件很小的。

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by TonyRL** [comment] 2024-12-30 03:39
Duplicate of #978

**Closed** 2024-12-30 03:45 UTC
Labels: enhancement
