### ISSUE TITLE
Feature Request: Allow Pinning or Custom Sorting of Feed Groups in the Subscription List

### ISSUE THREAD

**Issue by Hunya2077** [RSSNext/Follow#1582] opened 2024-11-12 18:28 UTC
### Description
I would like to propose a feature that would improve the organization of feed groups within the subscription list. Specifically, adding options to **pin certain groups to the top** or **customize the order of groups** would greatly enhance usability, particularly for users managing multiple feed groups.

### Feature Request
1. **Pinning Groups**: Enable users to pin specific feed groups so they always appear at the top of the list.
2. **Custom Group Sorting**: Provide an option for users to manually rearrange the order of feed groups in the subscription list, allowing for a customized organization that suits individual preferences.

### Expected Behavior
- Users can **pin preferred groups** to ensure quick access at the top of the subscription list.
- Users have **manual control over group sorting**, enabling a personalized, organized layout for their feed groups.

### Benefits
Implementing this feature would streamline workflows and make feed management and prioritization easier, especially for users with extensive subscriptions.

Thank you for considering this suggestion!

### Suggested solution

In the subscription management module, we could add options for pinning groups and manually adjusting group order. This might include adding drag-and-drop sorting functionality or a settings option where users can define group order.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by hyoban** [comment] 2024-11-13 12:20
Duplicate of #276

Let's track this issue there.

**Closed by hyoban** 2024-11-13 12:20 UTC
Labels: enhancement
