### ISSUE TITLE
哔哩哔哩可以订阅up主动态却无法订阅投稿

### ISSUE THREAD

**Issue by sep-21** [RSSNext/Follow#678] opened 2024-09-28 02:18 UTC
### Describe the bug

会显示出错

### Feed Info

宋仁和

### App Type

Electron / App

### Version

0.0.1-alpha.18

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment] 2024-10-28 18:38
Duplicate of #721

**Closed by DIYgod** 2024-10-28 18:38 UTC
