### ISSUE TITLE
Other people’s subscription content appears in the account

### ISSUE THREAD

**Issue by yanan-wyze** [RSSNext/Follow#1191] opened 2024-10-28 02:33 UTC
### Describe the bug

![image](https://github.com/user-attachments/assets/4e637275-7af8-4414-b18d-2da28b82e3ba)
订阅源莫名奇妙的多出一些未知的文章
![image](https://github.com/user-attachments/assets/449c345a-c49f-4095-9eb9-462e632644b7)
还无法操作

### Feed Info

71890977810318363

57597985421170688

57597985421170689

### App Type

Web

### Version

 0.1.1-beta.0

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-28 02:50
Duplicate of #1190, let us track the issue there

**Closed by hyoban** 2024-10-28 02:50 UTC
