### ISSUE TITLE
Add a card mode for articles

### ISSUE THREAD

**Issue by MatrixA** [RSSNext/Follow#2167] opened 2024-12-15 13:58 UTC
### Clear and concise description of the problem

Currently, articles only list in one column, so it's not so efficient if I have hundreds of news to read. 

### Suggested solution

If it have card mode, then the list will expand into many grids, and I can view headlines to quick through news. I believe it's a quite useful feature to beat existing other products like inoreader. I will switch into FOLLOW if it can support this feature asap.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by FHU-yezi** [comment] 2024-12-17 07:50
By the way it is better to use AI summary instead of the first part of article's content.

But we need to deal with the LLM latency and far more request to the server when we scoll down.

**Comment by TonyRL** [comment] 2024-12-30 16:36
Duplicate of #1298

**Closed** 2024-12-31 01:19 UTC
Labels: enhancement
