### ISSUE TITLE
Error in fetching feed: rsshub://twitter/keyword/finance

### ISSUE THREAD

**Issue by yongliangliu** [RSSNext/Follow#1374] opened 2024-11-04 03:22 UTC
### Info:

Feed URL:
```
rsshub://twitter/keyword/finance
```

Error:
```
Feed fetch error: [GET] "http://10.1.32.41/twitter/keyword/finance?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.0.1-alpha.22
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.22 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment] 2024-11-04 09:05
Duplicate of #740

**Closed by hyoban** 2024-11-04 09:05 UTC
