### ISSUE TITLE
Manually specify the encoding of the rss feed

### ISSUE THREAD

**Issue by molingyu** [RSSNext/Follow#586] opened 2024-09-23 08:49 UTC
### Clear and concise description of the problem

Many old websites do not use utf8 for RSS subscriptions, and the feed format they use is also very old, which results in the inability to correctly identify the encoding. I hope to provide a function to manually specify the encoding format of the subscription source to solve the problem of garbled characters in old RSS sources.

e.g. https://blog.codingnow.com/atom.xml

![6f5550954828cf4e21065594940cd04c](https://github.com/user-attachments/assets/9468f731-6699-43e5-8e9f-cddae397c852)

### Suggested solution

null

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment] 2024-09-23 08:53
Duplicate of #290

**Closed by hyoban** 2024-09-23 08:53 UTC
Labels: enhancement
