### ISSUE TITLE
The categories in sidebar not work after turn off "Reduce motion"

### ISSUE THREAD

**Issue by siygle** [RSSNext/Follow#285] opened 2024-09-07 08:37 UTC
### Describe the bug

The categories will change following the current panel in the sidebar in the default behavior. However, it won't work if the "Reduce motion" had been turned off.

### Feed Info

No related to the Feed.

### Reproduction Video

https://github.com/user-attachments/assets/21e64606-a2e6-4e64-a108-a9bc6c7a3247

### App Type

Electron / App

### Version

0.0.1-alpha.10

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-09-07 08:54
Duplicate of #281

**Closed by hyoban** 2024-09-07 08:54 UTC

**Comment by siygle** [comment] 2024-09-07 09:00
Sorry for the inconvenience, should search the issue list more carefully. 🤦🙇
