### ISSUE TITLE
B 站订阅源失效

### ISSUE THREAD

**Issue by thirteenkai** [RSSNext/Follow#728] opened 2024-09-30 10:37 UTC
### Describe the bug

B 站的订阅经常失效

### Feed Info

43114233109598208

### App Type

Electron / App

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-09-30 11:52
Duplicate of #721, let's track it there

**Closed by hyoban** 2024-09-30 11:52 UTC
