### ISSUE TITLE
Error in fetching feed: rsshub://xiaohongshu/user/265397237/collect

### ISSUE THREAD

**Issue by z-zhiwei** [RSSNext/Follow#1703] opened 2024-11-22 03:37 UTC
### Info:

Feed URL:
```
rsshub://xiaohongshu/user/265397237/collect
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/xiaohongshu/user/265397237/collect?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `YVWrNatddThVR8qa6DG88`

**Comment by hyoban** [comment] 2024-11-22 05:31
Duplicate of #1662

**Closed by hyoban** 2024-11-22 05:31 UTC
