### ISSUE TITLE
Youtube Video cannot play!Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by sonce** [RSSNext/Follow#2278] opened 2024-12-21 01:55 UTC
### Clear and concise description of the problem

Sign in to confirm you’re not a bot
This helps protect our community. [Learn more](https://support.google.com/youtube/answer/3037019#zippy=%2Ccheck-that-youre-signed-into-youtube)

![Image](https://github.com/user-attachments/assets/1484cf75-dd3b-4bfa-90ab-696ec7ba47ee)

swith to Browser and try to login,show this window.
![Image](https://github.com/user-attachments/assets/45c6df45-5047-427f-a518-fcb1ab49d1dc)

and close it and input email ,when click next button
![Image](https://github.com/user-attachments/assets/dfe4f88b-9917-414f-9298-eec171904a61)

### Suggested solution

watch youtube video in Follow

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by TonyRL** [comment] 2024-12-21 03:01
Duplicate of #1451

**Closed** 2024-12-23 12:17 UTC
Labels: enhancement
