### ISSUE TITLE
Image/Video View, Adjust Grid Preview Size.

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1243] opened 2024-10-30 08:16 UTC
### Clear and concise description of the problem

There is no way to do this at the moment, the image preview size is related to the program window size.

### Suggested solution

👇

https://github.com/user-attachments/assets/ba3477e5-9823-4d24-91af-936f091626e3

👇
- Control for the grid image size slider, similar to the effect found in Google Photos.
- Applicable to images and videos

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment] 2024-10-30 08:33
Duplicate of #1183

**Comment by EnterMan123** [comment] 2024-10-30 08:38
👇

https://github.com/user-attachments/assets/bdb4d059-c59f-4b79-bf0b-60e0653a584c


👇
- Control for the grid image size slider, similar to the effect found in Google Photos.
- Applicable to images and videos

**Comment by hyoban** [comment] 2024-11-26 15:28
Fixed in https://github.com/RSSNext/Follow/commit/0e0ce843235f01f33f4c5b9708aa67dac5901b46

**Closed by hyoban** 2024-11-26 15:28 UTC
Labels: enhancement

**Comment by EnterMan123** [comment] 2024-12-02 23:52
很棒的更新。不过发现个问题，程序关闭后重新启动时，列数重置为最大值。例如，我使用 3 列，关闭程序重新启动后变成为 6 列最大值。不能记住先前的习惯设置
