### ISSUE TITLE
The latest version cannot play Bilibili videos

### ISSUE THREAD

**Issue by SandmanFMJ** [RSSNext/Follow#1128] opened 2024-10-25 02:55 UTC
### Describe the bug

最新版本无法播放B站视频

### Feed Info

更新到最新版本以后，无法播放，老版本还可以播放

### Reproduction Video

![aff2ca27dfc1e5095eaa2e9023dae88](https://github.com/user-attachments/assets/fb747973-d891-4b20-99f1-15275e17024a)

### App Type

Electron / App

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-25 03:00
Duplicate of #1086, This has been fixed

**Closed by hyoban** 2024-10-25 03:00 UTC
