### ISSUE TITLE
The close button of the picture display page coincides with the software close button of the Windows client

### ISSUE THREAD

**Issue by aquausora** [RSSNext/Follow#1221] opened 2024-10-29 08:57 UTC
### Describe the bug

图片展示页面的关闭按钮与Windows客户端的软件关闭按钮重合，无论在全屏还是小窗状态都是如此，非常容易造成误点，具体见截图右上角

### Feed Info

![屏幕截图 2024-10-29 165056](https://github.com/user-attachments/assets/72a49369-196f-4de2-8e09-17e847406ac8)

### App Type

Electron / App

### Version

v0.1.1-beta.1

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-29 09:02
Duplicate of #1184. Fixed in https://github.com/RSSNext/Follow/commit/dc855703289ac98db76f4a57760fcd66047b8dd1

**Closed by hyoban** 2024-10-29 09:02 UTC
