### ISSUE TITLE
Only 20 unread messages can be displayed

### ISSUE THREAD

**Issue by jochne** [RSSNext/Follow#1922] opened 2024-11-29 01:12 UTC
### Describe the bug

筛选未读时，闪现一下全部未读，然后就只能查看最新20条。

### Feed Info

全部

### Reproduction Video

https://github.com/user-attachments/assets/a368ca3b-a6c7-44bf-8c5f-c79b7abe5c25

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-11-29 04:09
Duplicate of #1918

**Closed by hyoban** 2024-11-29 04:09 UTC
