### ISSUE TITLE
文章排序按更新时间排序

### ISSUE THREAD

**Issue by acevsok** [RSSNext/Follow#743] opened 2024-10-02 01:44 UTC
### Clear and concise description of the problem

文章排序按更新时间排序 其实这个如果有了之前说的那个只显示当天更新的文章功能按钮也有了。

### Suggested solution

文章排序按更新时间排序，每天阅读的话 会用到的，偶尔会断一天，可以排序阅读。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment] 2024-11-13 14:56
Duplicate of #276

Let's track this issue there.

**Closed by hyoban** 2024-11-13 14:56 UTC
Labels: enhancement
