### ISSUE TITLE
Unable to switch to dark mode

### ISSUE THREAD

**Issue by syc0000000** [RSSNext/Follow#1186] opened 2024-10-27 19:24 UTC
### Describe the bug

在设置里无法正确将软件从浅色模式切换到深色模式，仅文字部分反色，界面颜色/背景色不变

### Feed Info

与feed没关系

### Reproduction Video

![recording](https://github.com/user-attachments/assets/7bd93ceb-8c55-40aa-beaf-48507a689055)
文字反色效果：
![image](https://github.com/user-attachments/assets/00016264-6944-4ed0-ab09-5dc2c0a7c3cc)

### App Type

Electron / App

### Version

0.1.1-beta.1

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-28 01:44
Duplicate of #1160. Fixed in https://github.com/RSSNext/Follow/pull/1157.

**Closed by hyoban** 2024-10-28 01:44 UTC
