### ISSUE TITLE
Error: (intermediate value)(intermediate value)(intermediate value) is not iterable

### ISSUE THREAD

**Issue by Nat30** [RSSNext/Follow#1341] opened 2024-11-03 02:27 UTC
### Error

(intermediate value)(intermediate value)(intermediate value) is not iterable

### Stack

```
TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at https://app.follow.is/assets/index-C9NttSqA.js:20:10197
    at Object.useMemo (https://app.follow.is/vendor/0-KGA-48pw.js:30:23228)
    at T.useMemo (https://app.follow.is/vendor/0-KGA-48pw.js:9:6193)
    at pm (https://app.follow.is/assets/index-C9NttSqA.js:20:10178)
    at vo (https://app.follow.is/vendor/0-KGA-48pw.js:30:16959)
    at Ka (https://app.follow.is/vendor/0-KGA-48pw.js:32:43681)
    at Ha (https://app.follow.is/vendor/0-KGA-48pw.js:32:39486)
    at sd (https://app.follow.is/vendor/0-KGA-48pw.js:32:39417)
    at Jr (https://app.follow.is/vendor/0-KGA-48pw.js:32:39276)
    at Du (https://app.follow.is/vendor/0-KGA-48pw.js:32:35697)
    at Fi (https://app.follow.is/vendor/0-KGA-48pw.js:32:36498)
    at mn (https://app.follow.is/vendor/0-KGA-48pw.js:30:3258)
    at https://app.follow.is/vendor/0-KGA-48pw.js:32:34047
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

**Comment by TonyRL** [comment] 2024-11-03 04:51
Duplicate of #1308

**Closed** 2024-11-04 08:02 UTC
