### ISSUE TITLE
Error in fetching feed: rsshub://xiaohongshu/user/5a12a7d54eacab58938f95d2/notes/

### ISSUE THREAD

**Issue by kzfidx** [RSSNext/Follow#1744] opened 2024-11-22 20:05 UTC
### Info:

Feed URL:
```
rsshub://xiaohongshu/user/5a12a7d54eacab58938f95d2/notes/
```

Error:
```
[GET] "https://api.follow.is/feeds?url=rsshub%3A%2F%2Fxiaohongshu%2Fuser%2F5a12a7d54eacab58938f95d2%2Fnotes%2F": <no response> Failed to fetch
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `x1AZwx8d2U2z3Ndy9G_oT`

**Comment by hyoban** [comment] 2024-11-25 06:58
Duplicate of https://github.com/RSSNext/Follow/discussions/1717

**Closed by hyoban** 2024-11-25 06:58 UTC
