### ISSUE TITLE
Elsevier期刊订阅出错

### ISSUE THREAD

**Issue by bereaarrow** [RSSNext/Follow#539] opened 2024-09-21 01:18 UTC
### Describe the bug

![rss](https://github.com/user-attachments/assets/778cf259-37df-475d-a26c-a1e546c36e2c)
Elsevier期刊订阅出错

### Feed Info

https://rss.sciencedirect.com/publication/science/1747938X

### Reproduction Video

https://rss.sciencedirect.com/publication/science/1747938X

### App Type

Electron / App

### Version

15

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-09-21 01:32
Duplicate of #454

**Closed** 2024-09-22 16:56 UTC
