### ISSUE TITLE
Export OPML for Category 

### ISSUE THREAD

**Issue by yusixian** [RSSNext/Follow#1136] opened 2024-10-25 06:10 UTC
### Clear and concise description of the problem

I want export opml of all feeds under one of my categories so that I can edit him to batch replace the rsshub address for other instances. 

I intend to submit a PR for this issue

### Suggested solution

<img width="306" alt="image" src="https://github.com/user-attachments/assets/ea5cba04-e5ba-44bb-89bd-aa0ff14aa59d">

Is it possible to put this function on the right-click menu of the category? Or will there be a better category management revamp in progress?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment] 2024-10-25 06:37
Is this a duplicate of #874 ?

**Comment by yusixian** [comment] 2024-10-25 07:11
> Is this a duplicate of #874 ?

Yes

**Closed** 2024-11-20 12:41 UTC
Labels: enhancement
