### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'iconClassName')

### ISSUE THREAD

**Issue by Damaer** [RSSNext/Follow#2182] opened 2024-12-16 17:05 UTC
### Error

Cannot read properties of undefined (reading 'iconClassName')

### Stack

```
TypeError: Cannot read properties of undefined (reading 'iconClassName')
    at file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:218:15935
    at Array.map (<anonymous>)
    at LoginModalContent (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:218:15424)
    at vu (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:42:18838)
    at Au (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:44:3477)
    at Ud (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:44:48994)
    at $d (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:44:43476)
    at U2 (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:44:43402)
    at jl (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:44:43249)
    at Wu (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:44:39287)
    at Dd (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:44:40180)
    at Pa (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:42:3505)
    at file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-DghQV9jg.js:44:37451
```

### Environment

**App Version**: 0.2.6-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.6-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `tDP9YsGIBKB-GJ94bXWX_`

### Sentry Trace ID
FKIMiCzRPaoD1Q9Sf1uqe

**Comment by TonyRL** [comment] 2024-12-16 18:03
Duplicate of #2180

**Closed** 2024-12-17 00:47 UTC
