### ISSUE TITLE
Wall Street Journal subscription failed

### ISSUE THREAD

**Issue by Geon97** [RSSNext/Follow#1037] opened 2024-10-21 03:00 UTC
### Describe the bug

"https://cn.wsj.com/zh-hans/rss"   链接在浏览器上可以正常打开，在Follow上401，科学上网和关闭科学上网出现的情况都一样。
Err:
"https://cn.wsj.com/zh-hans/rss": 401 HTTP Forbidden****

### Feed Info

![Dingtalk_20241021105053](https://github.com/user-attachments/assets/54446769-07fc-4525-a92c-a1abac06fc27)
Err:
"https://cn.wsj.com/zh-hans/rss": 401 HTTP Forbidden

### App Type

Web

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-10-21 03:19
Duplicate of #839

**Closed** 2024-10-21 03:23 UTC
