### ISSUE TITLE
Error: (intermediate value)(intermediate value)(intermediate value) is not iterable

### ISSUE THREAD

**Issue by zippy2005** [RSSNext/Follow#1522] opened 2024-11-09 02:12 UTC
https://feeds.appinn.com/appinns/  this site can’t be load

### Error

(intermediate value)(intermediate value)(intermediate value) is not iterable

### Stack

```
TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:456:15446
    at Object.useMemo (file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:71:26036)
    at react_production_min.useMemo (file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:10:7277)
    at SupportCreator (file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:456:15413)
    at Nh (file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:71:19019)
    at Vk (file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:73:48765)
    at Uk (file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:73:43991)
    at Tk (file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:73:43912)
    at Ik (file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:73:43752)
    at Nk (file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:73:39720)
    at Ek (file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:73:40622)
    at jg (file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:71:3546)
    at file:///C:/Users/Administrator/AppData/Local/Follow/app-0.2.0-beta1/resources/app.asar/dist/renderer/assets/main-C93ND4vY.js:73:37840
```

### Environment

**App Version**: 0.2.0-beta.1
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.1 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `MY3nBmwJ4N_fbWC-HN1-J`

### Sentry Trace ID
rM9ufhPAUHFxABka3VaCp

**Comment by TonyRL** [comment] 2024-11-09 02:20
Duplicate of #1515

**Closed** 2024-11-09 10:05 UTC
