### ISSUE TITLE
The closing position of the internal browser coincides with the closing position of the application

### ISSUE THREAD

**Issue by xoipz** [RSSNext/Follow#1210] opened 2024-10-29 01:46 UTC
### Describe the bug

在浏览图片、视频等需要遮罩（蒙层）时，通常会出现两个关闭按钮重叠的问题。
![image](https://github.com/user-attachments/assets/57c5cb4b-3386-4571-9001-29022a8a2740)

### Feed Info

rsshub://weibo/user/2142290703

### App Type

Electron / App

### Version

0.1.1-beta.1

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-10-29 01:50
Duplicate of #1184

**Closed** 2024-10-29 01:54 UTC
