### ISSUE TITLE
[bug] Some collections will not show up in "Collections"

### ISSUE THREAD

**Issue by Dengwii** [RSSNext/Follow#926] opened 2024-10-13 12:56 UTC
### Describe the bug

部分收藏的内容, 在"收藏"中没有显示

### Feed Info

rsshub://telegram/channel/CE_Observe

### Reproduction Video

https://github.com/user-attachments/assets/00d8d9b2-1042-4eaf-8e12-9be4e8a5a7c0

### App Type

Electron / App

### Version

0.0.1-alpha.21

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by FlyAboveGrass** [comment] 2024-10-25 06:35
same problem

**Comment by DIYgod** [comment] 2024-10-29 08:56
Duplicate of #925

**Closed by DIYgod** 2024-10-29 08:56 UTC
