### ISSUE TITLE
Error in fetching feed: rsshub://twitter/user/CivilDefenseTW

### ISSUE THREAD

**Issue by nsjcasuma** [RSSNext/Follow#1338] opened 2024-11-03 01:49 UTC
### Info:

Feed URL:
```
rsshub://twitter/user/CivilDefenseTW
```

Error:
```
抓取動態時發生錯誤: [GET] "http://10.1.32.41/twitter/user/CivilDefenseTW?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment] 2024-11-03 05:52
Duplicate of #740

**Closed** 2024-11-04 09:03 UTC
