### ISSUE TITLE
Error in fetching feed: https://rsshub.app/douyin/user/MS4wLjABAAAAV43nVIpXdZebO8a0dnFEeL9m2h3YL5K8rEVatlP0ov4vxiJlDjB8zHE41GWqtcbH

### ISSUE THREAD

**Issue by GeoffBao** [RSSNext/Follow#1667] opened 2024-11-19 11:50 UTC
### Info:

Feed URL:
```
https://rsshub.app/douyin/user/MS4wLjABAAAAV43nVIpXdZebO8a0dnFEeL9m2h3YL5K8rEVatlP0ov4vxiJlDjB8zHE41GWqtcbH
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/douyin/user/MS4wLjABAAAAV43nVIpXdZebO8a0dnFEeL9m2h3YL5K8rEVatlP0ov4vxiJlDjB8zHE41GWqtcbH?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `eywtrpIgxTVUKhehqn1YJ`

**Comment by hyoban** [comment] 2024-11-19 12:15
Duplicate of #1356

**Closed by hyoban** 2024-11-19 12:15 UTC
