### ISSUE TITLE
Error in fetching list: 66008546697676800

### ISSUE THREAD

**Issue by shenshei** [RSSNext/Follow#2117] opened 2024-12-11 18:50 UTC
### Info:

List ID:
```
66008546697676800
```

Error:
```
Cannot add property 66008546697676800, object is not extensible
```

### Environment

**App Version**: 0.2.6-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.6-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `kv7rw8Pb-9EIrk5hsEYsp`

**Comment by TonyRL** [comment] 2024-12-11 19:30
Duplicate of #1399

**Closed** 2024-12-12 03:07 UTC
