### ISSUE TITLE
Cannot fetch latest (2 days ago) feed

### ISSUE THREAD

**Issue by silencial** [RSSNext/Follow#1968] opened 2024-12-01 21:48 UTC
### Describe the bug

无法获取最新（两天之前）的 RSS，手动刷新也不行，但从`在新标签页中打开订阅源`可以看到最新。
取消订阅后重新添加也可以获取到最新。
网页、macOS 端都一样。

### Feed Info

https://www.ifanr.com/feed
rsshub://sspai/index

### Reproduction Video

![Image](https://github.com/user-attachments/assets/b0b62054-7f0f-454d-940b-05af66bbbf27)

### Environment

**App Version**: 0.2.5-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.5-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `LWRpFlO3HZvFrlj4rRTcB`
**Renderer**: 0.2.5-beta.0

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-12-02 01:11
Duplicate of #1679

**Closed by hyoban** 2024-12-02 01:11 UTC
