### ISSUE TITLE
Error in fetching feed: https://navi.cnki.net/knavi/rss/ZHER?pcode=CJFD,CCJD

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [RSSNext/Follow#1309] opened 2024-11-02 01:38 UTC
### Info:

Feed URL:
```
https://navi.cnki.net/knavi/rss/ZHER?pcode=CJFD,CCJD
```

Error:
```
Feed 获取错误: [GET] "https://navi.cnki.net/knavi/rss/ZHER?pcode=CJFD,CCJD": <no response> fetch failed
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment] 2024-11-02 02:44
Duplicate of #733

**Closed** 2024-11-04 09:08 UTC
