### ISSUE TITLE
集成增加notion

### ISSUE THREAD

**Issue by jack-wz** [RSSNext/Follow#387] opened 2024-09-14 02:31 UTC
### Clear and concise description of the problem

集成增加notion功能

### Suggested solution

集成增加notion功能

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by 2019YKL** [comment] 2024-09-15 05:55
+1 期待这个功能。

**Comment by muserole** [comment] 2024-09-18 08:59
+1 期待这个功能。

**Comment by DIYgod** [comment] 2024-10-28 17:53
Duplicate of #161

**Closed by DIYgod** 2024-10-28 17:53 UTC
Labels: enhancement
