### ISSUE TITLE
导出后文件夹结构丢失|The folder structure is lost after exporting

### ISSUE THREAD

**Issue by Jiang10086** [RSSNext/Follow#874] opened 2024-10-11 04:24 UTC
### Clear and concise description of the problem

导出为OPML后，原来follow中的文件夹信息丢失，只剩下文章、社交媒体和图片等分类。但是订阅源多的时候，单独的视图中也要分文件夹，比如文章这一视图中的不同主题订阅源可以放入不同文件夹，导出后丢失了这一信息挺可惜的。不过follow订阅源分类有两个层级，即「视图」和「文件夹」，而OPML好像只支持一个层级，协调和兼容确实不好弄

After exporting to OPML, the folder structure in Follow is lost, leaving only categories like articles, social media, and images. However, when there are many subscriptions, it is necessary to organize them into folders within each individual view. For example, different themed subscriptions under the "Articles" view can be placed into different folders. It's quite unfortunate that this information is lost after exporting.

After all, Follow has a two-tier category system, with "Views" and "Folders," whereas OPML seems to only support a single tier. It's indeed challenging to reconcile and ensure compatibility between the two.

### Suggested solution

一种可能的方法：每种视图导出为单独的OPML文件。比如只在「文章」、「视频」和「音频」有订阅源，那就导出三个OPML，分别对应这三种视图

One possible solution: export each view as a separate OPML file. For example, if there are subscriptions only in "Articles," "Videos," and "Audio," then export three OPML files, one for each of these views.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment] 2024-10-29 06:47
Duplicate of #1136

**Closed** 2024-12-31 08:48 UTC
Labels: enhancement
