### ISSUE TITLE
Error in fetching feed: rsshub://twitter/user/ticktick

### ISSUE THREAD

**Issue by Zerokei** [RSSNext/Follow#1670] opened 2024-11-19 13:46 UTC
### Info:

Feed URL:
```
rsshub://twitter/user/ticktick
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/ticktick?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `tF2Oye7lCeCMU0uEGaYFo`

**Comment by hyoban** [comment] 2024-11-19 13:49
Duplicate of #740

**Closed by hyoban** 2024-11-19 13:49 UTC
