### ISSUE TITLE
Abnormal Text Selection Style on Share Page

### ISSUE THREAD

**Issue by L33Z22L11** [RSSNext/Follow#1235] opened 2024-10-30 02:59 UTC
### Describe the bug

On the share page for user/subscription/list, selected text appears with a transparent background and white font color, which closely matches the page's background color. This reduces readability significantly and makes selected text difficult to distinguish in light color mode. Adjusting the selection style to improve contrast would enhance readability.

### Feed Info

- https://app.follow.is/share/users/Zhilu
- https://app.follow.is/share/feeds/62533754566736896
- https://app.follow.is/share/lists/72840182614552576

### App Type

Web

### Version

0.1.1-beta.1

### Operating System

Windows 11

### Browser Info

Microsoft Edge 130.0.2849.56

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by L33Z22L11** [comment] 2024-11-05 09:34
![Image](https://github.com/user-attachments/assets/fd58573c-b997-4ec0-9580-6a9068fffb54)

**Comment by Innei** [comment] 2024-11-05 10:50
![Image](https://github.com/user-attachments/assets/a8f4863c-c532-40b8-8770-f098be7bd1f3)

can't reproduce.

**Comment by L33Z22L11** [comment] 2024-11-05 10:51
> This reduces readability significantly and makes selected text difficult to distinguish in light color mode. 

It can be reproduced in light color mode.

**Comment by Innei** [comment] 2024-11-05 10:51
It's work on my Windows 11 chrome 130.0.6723.92

**Comment by Innei** [comment] 2024-11-05 10:53
![Image](https://github.com/user-attachments/assets/b9d9fdd6-174f-466b-b53a-a6a30d2bd4a8)

light mode also can't reproduce

**Comment by Innei** [comment] 2024-11-05 10:55
Can't reproduce both macOS and Windows. Closed this issue. If other users met this issue can re-open again.

**Comment by L33Z22L11** [comment] 2024-11-05 10:55
> ![Image](https://github.com/user-attachments/assets/b9d9fdd6-174f-466b-b53a-a6a30d2bd4a8)
> 
> light mode also can't reproduce

You may use _Dark Reader_ Chrome extention. Don't use the light color utility of extentions. You should trun to Chrome settings to switch to light color mode.

**Closed by Innei** 2024-11-05 10:55 UTC

**Comment by L33Z22L11** [comment] 2024-11-05 11:04
![Image](https://github.com/user-attachments/assets/30c11922-5dce-4495-a0cf-58ace718dba2)

Firefox is okay, but Edge (normal or `edge://flags/#force-color-profile` selected to sRGB) and  Chrome canary didn't give `background-color` of `::selection`.

![Image](https://github.com/user-attachments/assets/4ad3740f-2635-4c24-9cc0-c6d79131a998)

**Comment by L33Z22L11** [comment] 2024-11-05 11:14
- Microsoft Edge 130.0.2849.68 (Release) (64bit)
- Chrome 132.0.6820.0（Release）canary (64 bit)

In short, the usage of `var(--tw-bg-opacity)` from origin value `var(--fallback-a,oklch(var(--a)/var(--tw-bg-opacity)))` caused this. When `var(--tw-bg-opacity)` is replaced by a simple `1`, it behaves normally.

**Comment by L33Z22L11** [comment] 2024-12-11 02:52
It's related to https://github.com/tailwindlabs/tailwindcss/issues/15000 and fixed.
