### ISSUE TITLE
Hope the desktop client has a built-in translation feature

### ISSUE THREAD

**Issue by tahitimoon** [RSSNext/Follow#1071] opened 2024-10-23 06:42 UTC
### Clear and concise description of the problem

Hope the desktop client has a built-in translation feature, similar to Twitter's one-click translation, which makes it easy to view various articles and tweets

### Suggested solution

Hope the desktop client has a built-in translation feature, similar to Twitter's one-click translation, which makes it easy to view various articles and tweets

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment] 2024-10-23 06:52
Duplicate of #770

**Closed** 2024-10-23 07:02 UTC
Labels: enhancement
