### ISSUE TITLE
Image preview issue

### ISSUE THREAD

**Issue by Sandywangyu** [RSSNext/Follow#1237] opened 2024-10-30 03:27 UTC
### Describe the bug

1.长图无法放大，缩小，导致无法观看
2.图片关闭按钮与软件关闭按钮重叠，易导致误触
![1730258688944](https://github.com/user-attachments/assets/0e7a50d8-715b-44c1-b9b4-0b22222b6fc7)

### Feed Info

![image](https://github.com/user-attachments/assets/2476e27e-21d0-4c7b-a59f-63d698c001f3

### App Type

Electron / App

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-10-30 03:31
Duplicate of #1184

**Closed** 2024-10-30 03:32 UTC
