### ISSUE TITLE
Error in fetching feed: rsshub://twitter/user/COINAppRankBot

### ISSUE THREAD

**Issue by jonasqin** [RSSNext/Follow#1470] opened 2024-11-07 10:38 UTC
### Info:

Feed URL:
```
rsshub://twitter/user/COINAppRankBot
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/COINAppRankBot?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

Plus: All those twitter account that can not fetch feed also can not be transfered to uid in https://tweeterid.com/

**Comment by hyoban** [comment] 2024-11-07 10:47
Duplicate of #740

**Closed by hyoban** 2024-11-07 10:48 UTC
