### ISSUE TITLE
Request for feature allowing owner of subscription to forcely refresh feed

### ISSUE THREAD

**Issue by Allenyou1126** [RSSNext/Follow#1118] opened 2024-10-24 14:33 UTC
### Clear and concise description of the problem

As I changed the behavior of my RSS feed from outputing abscract of articles to outputing the full content, the feed fetched by Follow will be never updated.

### Suggested solution

I suggest to add a feature to allow feed owners to refresh their feed forcely.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment] 2024-10-25 00:57
We have restored the ability to update content and it should be updated with the next refresh. But the ability to reset the feed is still worth considering, this is a duplicate of #1018

**Closed by hyoban** 2024-10-25 00:57 UTC
Labels: enhancement

**Comment by CorrectRoadH** [comment] 2024-10-25 09:46
> We have restored the ability to update content and it should be updated with the next refresh. If not, please provide your feed info.

Does it regenerate the entire feed based on RSS.xml? For example, will some deleted blogs also disappear from the follow list?

**Comment by hyoban** [comment] 2024-10-25 09:53
No, we cannot simply delete entries that do not exist in RSS.xml. For example, some feeds limit the number of articles output.

**Comment by Allenyou1126** [comment] 2024-10-28 02:13
btw, will owner of feeds be allowed to change the feed link?
I refractored my blog and changed feed url from `/feed` to `/feed.xml`, how can I inform the subscribers to switch to the new URL?

**Comment by hyoban** [comment] 2024-10-28 02:36
If you handle the redirect correctly, we will automatically update the user subscriptions to the new feed.

**Comment by Allenyou1126** [comment] 2024-10-28 12:11
thanks, then i'll try to add a 301 redirect in my nginx configuration.
