### ISSUE TITLE
Follow cannot subscribe the rss of Journal from cnki.

### ISSUE THREAD

**Issue by yzy1228682367** [RSSNext/Follow#960] opened 2024-10-15 12:04 UTC
### Describe the bug

Follow cannot subscribe the rss of Journal from cnki. The Feed can be opened in China, but seem cannot be opened outside China. That’s maybe the reason why Follow cannot subscribe the rss of Journal from cnki.

### Feed Info

[法学研究](https://rss.cnki.net/kns/rss.aspx?Journal=LAWS&Virtual=knavi)

### App Type

Electron / App

### Version

1.0.0

### Operating System

macOS

### Browser Info

Arc 

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-10-15 12:39
Duplicate of #733

**Comment by hyoban** [comment] 2024-10-16 01:56
Thanks for your report, let us continue to track the problem in that issue

**Closed by hyoban** 2024-10-16 01:56 UTC
