### ISSUE TITLE
503 Service Unavailable for adding feed X.com and Instagram via RSSHub

### ISSUE THREAD

**Issue by pyx378952739** [RSSNext/Follow#1260] opened 2024-10-31 08:03 UTC
### Describe the bug

I copied links of x.com and instagram or I choose from the options below and input the account name, 
after a long loading ,it will appear 503 code. I guess it's may because of the high damage of rsshub using. 
![image](https://github.com/user-attachments/assets/0df09e6b-fd4a-4540-9cb2-6e547e37a3a6)

but the feed of xiaohongshu is easy to add

### Feed Info

any links of x.com and instagram 

### App Type

Electron / App

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by tang-hi** [comment] 2024-10-31 12:30
I also encountered this problem. 😢

**Comment by TonyRL** [comment] 2024-10-31 14:37
Duplicate of #740

**Closed** 2024-11-02 04:15 UTC
