### ISSUE TITLE
Looking forward to supporting translations

### ISSUE THREAD

**Issue by maxfrees** [RSSNext/Follow#1257] opened 2024-10-31 06:00 UTC
### Clear and concise description of the problem

Looking forward to supporting translations

### Suggested solution

Looking forward to supporting translations

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment] 2024-10-31 10:56
Duplicate of #1071

**Closed** 2024-11-02 04:17 UTC
Labels: enhancement
