### ISSUE TITLE
Pictures in messages in social media mode are enlarged with the scroll wheel

### ISSUE THREAD

**Issue by gitwuneng** [RSSNext/Follow#1003] opened 2024-10-18 01:21 UTC
### Clear and concise description of the problem

现在社交媒体模式下微博图片点击后是全屏状态，如果是长截图，图片内容无法看清，图片也无法再放大。

### Suggested solution

点击图片后增加滚轮放大功能

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment] 2024-10-29 09:30
Duplicate of #1183

**Closed by DIYgod** 2024-10-29 09:30 UTC
Labels: enhancement
