### ISSUE TITLE
Error in fetching feed: https://rsshub.app/twitter/user/osorii_

### ISSUE THREAD

**Issue by WAN-Gwg** [RSSNext/Follow#1766] opened 2024-11-23 22:34 UTC
### Info:

Feed URL:
```
https://rsshub.app/twitter/user/osorii_
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/osorii_?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `hr7pU_TPrPUOVlW2yIzyY`

**Comment by hyoban** [comment] 2024-11-25 06:59
Duplicate of https://github.com/RSSNext/Follow/discussions/1713

**Closed by hyoban** 2024-11-25 06:59 UTC
