### ISSUE TITLE
Error in fetching feed: rsshub://xiaohongshu/user/6284d7e0000000002102760a/notes

### ISSUE THREAD

**Issue by tian-Sun** [RSSNext/Follow#1676] opened 2024-11-20 09:42 UTC
### Info:

Feed URL:
```
rsshub://xiaohongshu/user/6284d7e0000000002102760a/notes
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/xiaohongshu/user/6284d7e0000000002102760a/notes?format=json": 500 Internal Server Error
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `BDOAt3FmxW6hAaKjbj1hC`

**Comment by hyoban** [comment] 2024-11-20 09:43
Duplicate of #1662

**Closed by hyoban** 2024-11-20 09:43 UTC
