### ISSUE TITLE
this button can not run

### ISSUE THREAD

**Issue by Webming19** [RSSNext/Follow#1484] opened 2024-11-08 01:16 UTC
### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

![Image](https://github.com/user-attachments/assets/e822ef10-2ef6-4b09-ae08-82054ba313d6)

close button can not run.

**Comment by TonyRL** [comment] 2024-11-08 01:23
Duplicate of #1311

**Closed** 2024-11-08 03:13 UTC
