### ISSUE TITLE
Need IOS,BRO!

### ISSUE THREAD

**Issue by whizsail** [RSSNext/Follow#1188] opened 2024-10-28 01:07 UTC
### Clear and concise description of the problem

if we have the ios version wil be the best!

### Suggested solution

if we have the ios version wil be the best!

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment] 2024-10-28 01:14
Duplicate of #972

**Closed by TonyRL** 2024-10-28 01:14 UTC
Labels: enhancement
