### ISSUE TITLE
Cannot subscribe to scientific journals

### ISSUE THREAD

**Issue by nilynaaa** [RSSNext/Follow#1195] opened 2024-10-28 03:13 UTC
### Describe the bug

I am engaged in scientific research and need to pay attention to some SCI journals, including SciencDrect, Wiley, springer, etc., as well as some Chinese science and technology journals.

### Feed Info

https://navi.cnki.net/knavi/rss/NYDX?pcode=CJFD,CCJD

### Reproduction Video

![image](https://github.com/user-attachments/assets/386a0a01-622d-4835-aaaa-2835b9afbd5c)

### App Type

Electron / App

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-28 03:31
Duplicate of #733

**Closed by hyoban** 2024-10-28 03:31 UTC
