### ISSUE TITLE
Windows下加载长文卡死

### ISSUE THREAD

**Issue by fwrite0920** [RSSNext/Follow#292] opened 2024-09-07 23:29 UTC
### Describe the bug

在加载长文的时候，会直接卡死

### Feed Info

https://isming.me/index.xml

### App Type

Electron / App

### Version

0.0.1-alpha。10

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment] 2024-09-09 15:03
This issue is caused by shiki.

https://github.com/shikijs/shiki/issues/772

**Comment by Innei** [comment] 2024-09-12 12:29
Fixed in next version

**Closed** 2024-09-13 05:53 UTC
Labels: release in next version
