### ISSUE TITLE
Error in fetching list: 71827830389997568

### ISSUE THREAD

**Issue by Adou0708** [RSSNext/Follow#2230] opened 2024-12-19 01:51 UTC
### Info:

List ID:
```
71827830389997568
```

Error:
```
Cannot add property 71827830389997568, object is not extensible
```

### Environment

**App Version**: 0.2.7-nightly.20241218
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.7-nightly.20241218 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `rwZq6UuBoBM_7EJqTW9hH`

**Comment by TonyRL** [comment] 2024-12-19 03:56
Duplicate of #1399

**Closed** 2024-12-19 07:18 UTC
