### ISSUE TITLE
Error in fetching feed: https://rsshub.app/douyin/user/MS4wLjABAAAABW9yHDOfCmUo9Lg0yrG1BF4PkoIiBzft_Ge7IcVpwR0

### ISSUE THREAD

**Issue by stelvetica** [RSSNext/Follow#1574] opened 2024-11-12 06:33 UTC
### Info:

Feed URL:
```
https://rsshub.app/douyin/user/MS4wLjABAAAABW9yHDOfCmUo9Lg0yrG1BF4PkoIiBzft_Ge7IcVpwR0
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/douyin/user/MS4wLjABAAAABW9yHDOfCmUo9Lg0yrG1BF4PkoIiBzft_Ge7IcVpwR0?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.0-beta.2
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `yVprchzCavINRMEAnRZpN`

**Comment by TonyRL** [comment] 2024-11-12 06:42
Duplicate of #1356

**Closed** 2024-11-12 06:45 UTC
