### ISSUE TITLE
The locally built wewe rss cannot read the content

### ISSUE THREAD

**Issue by cyx951211** [RSSNext/Follow#1137] opened 2024-10-25 06:15 UTC
### Describe the bug

用本地搭建的wewe rss  导出opml文件 用Follow无法读取内容 
显示内容为：
源失效：1天前
[GET] "http://localhost:4000/feeds/MP_WXS_3070156923.atom" <no response> fetch
failed**

### Feed Info

[GET] "http://localhost:4000/feeds/MP_WXS_3070156923.atom" <no response> fetch
failed

### Reproduction Video

<img width="748" alt="image" src="https://github.com/user-attachments/assets/930e64dd-c4d3-4c02-a03e-5acd5d221dad">

### App Type

Electron / App

### Operating System

macOS

### Browser Info

12.6.1

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-10-28 02:06
Duplicate of #1189

**Closed** 2024-10-28 02:10 UTC
