### ISSUE TITLE
Feed 获取错误: [GET] "http://10.1.32.41/twitter/list/1848270402398593144?format=json": 503 Service Unavailable

### ISSUE THREAD

**Issue by iar** [RSSNext/Follow#1044] opened 2024-10-21 09:26 UTC
### Describe the bug

无法读取Twitter列表

### Feed Info

rsshub://twitter/list/1848270402398593144

### App Type

Web

### Version

0.0.1-alpha.21

### Operating System

Windows 11

### Browser Info

Microsoft Edge 版本 126.0.2592.102 (正式版本) (64 位)

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-21 11:28
Duplicate of #740

**Closed by hyoban** 2024-10-21 11:28 UTC
