### ISSUE TITLE
Error: (intermediate value)(intermediate value)(intermediate value) is not iterable

### ISSUE THREAD

**Issue by clearloveqi** [RSSNext/Follow#1312] opened 2024-11-02 03:51 UTC
### Error

(intermediate value)(intermediate value)(intermediate value) is not iterable

### Stack

```
TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:426:12964
    at Object.useMemo (file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:71:26036)
    at react_production_min.useMemo (file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:10:7277)
    at SupportCreator (file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:426:12931)
    at Nh (file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:71:19019)
    at Vk (file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:48765)
    at Uk (file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:43991)
    at Tk (file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:43912)
    at Ik (file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:43752)
    at Nk (file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:39720)
    at Ek (file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:40622)
    at jg (file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:71:3546)
    at file:///C:/Users/water/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:37840
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment] 2024-11-02 04:08
Duplicate of #1308

**Closed** 2024-11-02 04:10 UTC
