### ISSUE TITLE
local-first

### ISSUE THREAD

**Issue by landsman** [RSSNext/Follow#2245] opened 2024-12-19 08:16 UTC
### Clear and concise description of the problem

Hi, I don't want to log in. I want my data locally.

### Suggested solution

Allow me to do not login, provide local database with export feature.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by TonyRL** [comment] 2024-12-21 03:00
Duplicate of #192

**Closed** 2024-12-24 01:46 UTC
Labels: enhancement
