### ISSUE TITLE
加载简体中文语言包失败

### ISSUE THREAD

**Issue by melorious** [RSSNext/Follow#491] opened 2024-09-19 02:15 UTC
### Describe the bug

![image](https://github.com/user-attachments/assets/873d6a93-6fbe-4a04-96fb-91f3c423b9f3)

### Feed Info

no feed

### App Type

Electron / App

### Version

0.0.01-alpha.13

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-09-19 02:48
Duplicate of #447

**Closed** 2024-09-19 03:02 UTC

**Comment by scarsu** [comment] 2024-09-19 11:57
> > [FOL-197 加载简体中文语言包失败](https://linear.app/follow-app/issue/FOL-197/%E5%8A%A0%E8%BD%BD%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%E8%AF%AD%E8%A8%80%E5%8C%85%E5%A4%B1%E8%B4%A5)
> 
> 无法访问这个链接，登陆后提示：You don't have access to this workspace.
> 
> PIease contact the workspace admin to gain access.

same

![image](https://github.com/user-attachments/assets/e2e747ad-fa4b-47b1-81ae-6e078a1b02d5)
