### ISSUE TITLE
Duplicate deduction issue

### ISSUE THREAD

**Issue by yadihaoku** [RSSNext/Follow#888] opened 2024-10-12 01:56 UTC
### Describe the bug

For the same source, the fee is deducted twice at the same time

### Feed Info

![20241012-095441](https://github.com/user-attachments/assets/1323ab43-fd05-405b-bfed-3ff7ca64d581)

### App Type

Web

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-12 01:58
Is this a duplicate of #881?

**Closed** 2024-10-29 06:46 UTC
