### ISSUE TITLE
Error in fetching feed: https://rsshub.app/twitter/user/lifemademore

### ISSUE THREAD

**Issue by GeoffBao** [RSSNext/Follow#1402] opened 2024-11-05 03:40 UTC
### Info:

Feed URL:
```
https://rsshub.app/twitter/user/lifemademore
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/lifemademore?format=json": <no response> fetch failed
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment] 2024-11-05 03:41
Duplicate of #740

**Closed by hyoban** 2024-11-05 03:41 UTC
