### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by heran11011** [RSSNext/Follow#1517] opened 2024-11-09 01:17 UTC
### Error

Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### Stack

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:25956)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26187)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:25859)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26728)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:25859)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:25859)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26728)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26404)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
    at ja (https://app.follow.is/vendor/0-UnCfif0S.js:32:26187)
    at Xe (https://app.follow.is/vendor/0-UnCfif0S.js:32:25667)
```

### Environment

**App Version**: 0.2.0-beta.1
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `-sFHktdNLb5apxZ0PU0J1`

### Sentry Trace ID
E13gmibgr6-UWmpP1s0qq

**Comment by hyoban** [comment] 2024-11-26 11:41
Duplicate of #1331

Feel free to help us troubleshoot the issue by providing more information on how to reproduce it in #1294

**Closed by hyoban** 2024-11-26 11:41 UTC
