### ISSUE TITLE
Error in fetching feed: rsshub://xiaohongshu/user/5c60b272000000001a0088af/notes

### ISSUE THREAD

**Issue by cnwubf** [RSSNext/Follow#1637] opened 2024-11-17 05:04 UTC
### Info:

Feed URL:
```
rsshub://xiaohongshu/user/5c60b272000000001a0088af/notes
```

Error:
```
[GET] "https://api.follow.is/feeds?url=rsshub%3A%2F%2Fxiaohongshu%2Fuser%2F5c60b272000000001a0088af%2Fnotes": <no response> Failed to fetch
```

### Environment

**App Version**: 0.2.1-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.1-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `RKzf-hgJblYiOxL9oqqZq`

**Comment by hyoban** [comment] 2024-11-22 11:23
Duplicate of #1662

**Closed by hyoban** 2024-11-22 11:23 UTC
