### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by leslieyeo** [RSSNext/Follow#2099] opened 2024-12-11 02:18 UTC
### Error

Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### Stack

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26043)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26280)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:25943)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26823)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:25943)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:25943)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26823)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26280)
    at Lr (https://app.follow.is/vendor/0-270N51eK.js:40:25749)
```

### Environment

**App Version**: 0.2.6-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `0EFoFKyS2ZF8Gb5fFr6gy`

### Sentry Trace ID
-vZEubp5fDd6lUeO7wBPy

**Comment by TonyRL** [comment] 2024-12-11 09:50
Duplicate of #2027

**Closed** 2024-12-19 07:17 UTC
