### ISSUE TITLE
white screen when click import

### ISSUE THREAD

**Issue by saccohuo** [RSSNext/Follow#255] opened 2024-08-31 17:19 UTC
### Describe the bug

The windows becomes white when click on "import".

### Feed Info

NA

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment] 2024-09-01 15:13
Can't reproduction, upload a video reproduction plz.

**Comment by saccohuo** [comment] 2024-09-01 15:20
![follow-import-white-screen](https://github.com/user-attachments/assets/a95519c8-137f-4909-b1e8-bd829d0ec6c8)

@Innei  Here is the screenshot.

**Comment by Innei** [comment] 2024-09-03 05:07
Sorry, I can't reproduce this. The screenshots you provided don't yield any useful information either.

**Comment by Innei** [comment] 2024-09-03 05:08
Can you open the dev tools (it should be Control + Shift + I for Windows) and copy the error trace stack?

**Comment by Innei** [comment] 2024-09-03 07:31
Thank you for your report, this bug fixes will be released in the next version.

**Closed** 2024-09-03 07:31 UTC
Labels: help wanted
