### ISSUE TITLE
Error in fetching feed: rsshub://twitter/user/%40yupiop12

### ISSUE THREAD

**Issue by simba119** [RSSNext/Follow#1482] opened 2024-11-07 16:54 UTC
### Info:

Feed URL:
```
rsshub://twitter/user/%40yupiop12
```

Error:
```
[GET] "https://api.follow.is/feeds?url=rsshub%3A%2F%2Ftwitter%2Fuser%2F%2540yupiop12": <no response> Failed to fetch
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment] 2024-11-07 16:57
Duplicate of #740

**Closed** 2024-11-08 03:12 UTC
