### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'image')

### ISSUE THREAD

**Issue by luka-mimi** [RSSNext/Follow#1790] opened 2024-11-24 14:47 UTC
### Error

Cannot read properties of undefined (reading 'image')

### Stack

```
TypeError: Cannot read properties of undefined (reading 'image')
    at SubscriptionItems (https://app.follow.is/assets/user-profile-modal-B-c4PSMe.js:63:96)
    at Nh (https://app.follow.is/vendor/0-EeJr3raE.js:3399:7)
    at Vk (https://app.follow.is/vendor/0-EeJr3raE.js:6342:11)
    at Uk (https://app.follow.is/vendor/0-EeJr3raE.js:6036:11)
    at Tk (https://app.follow.is/vendor/0-EeJr3raE.js:6030:26)
    at Ik (https://app.follow.is/vendor/0-EeJr3raE.js:6015:7)
    at Nk (https://app.follow.is/vendor/0-EeJr3raE.js:5746:7)
    at Ek (https://app.follow.is/vendor/0-EeJr3raE.js:5800:28)
    at jg (https://app.follow.is/vendor/0-EeJr3raE.js:2708:15)
    at Wk (https://app.follow.is/vendor/0-EeJr3raE.js:6134:3)
    at Pk (https://app.follow.is/vendor/0-EeJr3raE.js:6077:36)
    at Gk (https://app.follow.is/vendor/0-EeJr3raE.js:5733:11)
    at J2 (https://app.follow.is/vendor/0-EeJr3raE.js:425:19)
    at MessagePort.R2 (https://app.follow.is/vendor/0-EeJr3raE.js:453:13)
```

### Environment

**App Version**: 0.2.4-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `BoHSy_8ArZyqHnb1t4Bgo`

### Sentry Trace ID
rdgdkMx7PUhxcv_tKJ5gw

**Comment by TonyRL** [comment] 2024-11-24 15:27
Duplicate of #1785

**Closed** 2024-11-25 07:47 UTC
