### ISSUE TITLE
Sort of articles

### ISSUE THREAD

**Issue by wms6017** [RSSNext/Follow#2005] opened 2024-12-04 13:46 UTC
### Clear and concise description of the problem

The current order of articles is new to old, but I think there are many people like me who prefer the opposite order

### Suggested solution

Added ability to switch article sorting from old to new

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by hyoban** [comment] 2024-12-04 14:03
Duplicate of #276

**Closed by hyoban** 2024-12-04 14:03 UTC
Labels: enhancement
