### ISSUE TITLE
Error in fetching list: 61315142157070336

### ISSUE THREAD

**Issue by lworld0x00** [RSSNext/Follow#1332] opened 2024-11-02 15:27 UTC
### Info:

List ID:
```
61315142157070336
```

Error:
```
Cannot add property 61315142157070336, object is not extensible
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment] 2024-11-05 03:36
Can you provide more info about how to reproduce this issue?

**Comment by hyoban** [comment] 2024-11-05 04:10
Duplicate of #1399, since there is more information there, let's track the issue there

**Closed by hyoban** 2024-11-05 04:10 UTC
