### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by ppzoe** [RSSNext/Follow#1945] opened 2024-11-30 19:23 UTC
### Error

Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### Stack

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26043)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26280)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:25943)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26823)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:25943)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:25943)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26823)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26498)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
    at qa (https://app.follow.is/vendor/0-D5-66EFx.js:40:26280)
    at Lr (https://app.follow.is/vendor/0-D5-66EFx.js:40:25749)
```

### Environment

**App Version**: 0.2.5-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `QvTX8COPYVvz4qIDsnReu`

### Sentry Trace ID
J5bKvRMa_WUxLQz-b2R9d

**Comment by TonyRL** [comment] 2024-12-18 15:01
Duplicate of #2027

**Closed** 2024-12-19 07:16 UTC
