### ISSUE TITLE
Cannot get Exponential View's update

### ISSUE THREAD

**Issue by novac42code** [RSSNext/Follow#264] opened 2024-09-02 10:35 UTC
### Describe the bug

Couldn't get items from this feed. Same on Mac version and Windows. 
![image](https://github.com/user-attachments/assets/a1300dc6-61c0-411f-a199-f9052ead59fb)
![image](https://github.com/user-attachments/assets/ac62fccd-9368-44f4-b298-c53a63011423)

### Feed Info

https://www.exponentialview.co/feed

### App Type

Electron / App

### Version

0.0.1 Alpha9

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-09-02 11:09
Duplicate of #253

**Closed** 2024-09-03 11:16 UTC
