### ISSUE TITLE
Unable to log in on mac app

### ISSUE THREAD

**Issue by GHOST1834** [RSSNext/Follow#2021] opened 2024-12-05 12:13 UTC
### Describe the bug

For the latest two nightly versions of mac, every time I open the app it just shows "failed to set voice", and leaves no option for logging in. Hence I can only use the web version as a temporary substitute.

### Feed Info

Not feed problem but app problem

### Reproduction Video

![Image](https://github.com/user-attachments/assets/39657c1a-0930-4875-aa0c-0d65399b80ff)

### Environment

**App Version**: 0.2.5-nightly.20241204
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.5-nightly.20241204 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `gTAWIJ_mYxpQmG18YDSzm`
**Renderer**: 0.2.5-nightly.20241204

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-12-05 12:21
Duplicate of #1990

**Closed by hyoban** 2024-12-05 12:21 UTC
