### ISSUE TITLE
Error in fetching feed: rsshub://twitter/user/quant_arb

### ISSUE THREAD

**Issue by hhr114** [RSSNext/Follow#1556] opened 2024-11-10 15:38 UTC
### Info:

Feed URL:
```
rsshub://twitter/user/quant_arb
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/quant_arb?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.0-beta.2
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
**Env**: web
**Browser**: Microsoft Edge
**Session Trace Id**: `4JLazRX1C_jZYTr90G7DC`

**Comment by TonyRL** [comment] 2024-11-10 22:33
Duplicate of #740

**Closed** 2024-11-11 02:20 UTC
