### ISSUE TITLE
Error in fetching feed: https://rsshub.app/twitter/user/skillshare

### ISSUE THREAD

**Issue by GeoffBao** [RSSNext/Follow#1743] opened 2024-11-22 18:13 UTC
### Info:

Feed URL:
```
https://rsshub.app/twitter/user/skillshare
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/skillshare?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `8JQeQE8pqv5m1eB8Cdk6Y`

**Comment by hyoban** [comment] 2024-11-25 06:57
Duplicate of https://github.com/RSSNext/Follow/discussions/1713

**Closed by hyoban** 2024-11-25 06:57 UTC
