### ISSUE TITLE
Error in fetching feed: rsshub://twitter/user/HODL15Capital

### ISSUE THREAD

**Issue by jonasqin** [RSSNext/Follow#1353] opened 2024-11-03 11:02 UTC
### Info:

Feed URL:
```
rsshub://twitter/user/HODL15Capital
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/HODL15Capital?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment] 2024-11-03 11:10
Duplicate of #740

**Closed** 2024-11-04 08:10 UTC
