### ISSUE TITLE
Not open source?

### ISSUE THREAD

**Issue by sm18lr88** [RSSNext/Follow#360] opened 2024-09-12 02:29 UTC
### Describe the bug

App doesn't allow users to use it without the invitation code, even when we build it from the source.

Please release the app from this lock.

This issue is not a duplicate from #126 where users were only asking for the invitation code.

### Feed Info

none

### App Type

Electron / App

### Version

0.0.1-alpha.10-windows-x64

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-09-12 02:39
Duplicate of #34

**Closed** 2024-09-12 02:47 UTC
