### ISSUE TITLE
Bugs in some specific feeds

### ISSUE THREAD

**Issue by Marcus-zh** [RSSNext/Follow#1159] opened 2024-10-26 07:41 UTC
### Describe the bug

When I open some feeds in electron app,the page throw the error:
> dayjs.duration is not a function
> Follow has a temporary problem, click the button below to try reloading the app or
> another solution?

I don't know how to deal to it,so I create a issue.
Nothing happend in web.But in electron.

### Feed Info

https://app.follow.is/share/users/72617922693905408

### Reproduction Video

![recording](https://github.com/user-attachments/assets/f825a774-23fc-4e71-a8d6-9339ac454f4b)

### App Type

Electron / App

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-26 09:54
Duplicate of #1153

**Closed by hyoban** 2024-10-26 09:54 UTC
