### ISSUE TITLE
Mac端App的暗黑模式显示异常

### ISSUE THREAD

**Issue by uniqueww** [RSSNext/Follow#786] opened 2024-10-06 12:01 UTC
### Describe the bug

如题App的暗黑模式显示的背景依旧是白色且字体为灰色，夜间使用十分不舒服，望改进，感谢！
<img width="1341" alt="image" src="https://github.com/user-attachments/assets/e783fee2-37d2-4a9a-b94c-bb96df11d271">

### Feed Info

41342818708527107

### App Type

Electron / App

### Version

0.0.1-alpha.19

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-06 12:43
Fixed in https://github.com/RSSNext/Follow/commit/6697ff58b30a1f4838fdca3820c725457ec483d4
Duplicate of #763

**Closed by hyoban** 2024-10-06 12:43 UTC
