### ISSUE TITLE
Close buttons overlap

### ISSUE THREAD

**Issue by Link-32** [RSSNext/Follow#1219] opened 2024-10-29 08:31 UTC
### Describe the bug

The close button in the upper right corner of open pictures and videos overlaps with the close button of the app. When closing the video, the app will be closed directly.

### Feed Info

![image](https://github.com/user-attachments/assets/468c4e45-2263-441b-a636-4f9096a575b7)
![close button](https://github.com/user-attachments/assets/a9e5247e-0f66-40f3-beb5-a5ef3c381f98)

### App Type

Electron / App

### Version

0.1.1-beta.1

### Operating System

Windows 10

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-29 08:42
Duplicate of #1184. Fixed in https://github.com/RSSNext/Follow/commit/dc855703289ac98db76f4a57760fcd66047b8dd1

**Closed by hyoban** 2024-10-29 08:42 UTC
