### ISSUE TITLE
I hope that the block rules for actions can be expanded to include categories.

### ISSUE THREAD

**Issue by willzhang0803** [RSSNext/Follow#659] opened 2024-09-27 03:24 UTC
### Clear and concise description of the problem

"I hope that the block rules for actions can be expanded to include categories. Currently, all conditions must be met simultaneously. I'd like to add an 'OR' option for selection. If possible, I hope it can reference Inoreader's filter logic, where you can choose to either 'remove articles' or 'keep articles'. Below these options, the conditions should allow for selecting either 'AND' or 'OR' logic."
Thanks.

### Suggested solution

Adding categories to block rules
Introducing an 'OR' option in addition to the existing 'AND' logic
Allowing users to choose between 'remove articles' and 'keep articles'

### Additional context

![QQ20240927-112405](https://github.com/user-attachments/assets/7f135ffc-85c0-4c43-930b-494482a0c352)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment] 2024-10-28 18:39
Duplicate of #592

**Closed by DIYgod** 2024-10-28 18:39 UTC
Labels: enhancement
