### ISSUE TITLE
The position of the title on the article list page changes frequently. 标题疯狂抖动

### ISSUE THREAD

**Issue by y4code** [RSSNext/Follow#274] opened 2024-09-05 20:47 UTC
### Describe the bug

RT

### Feed Info

Feed: https://news.ycombinator.com/rss
Entry ID: 54593048778700805
Link: https://electrek.co/2024/09/05/i-sold-all-my-tesla-shares-tsla-why/

### Reproduction Video

https://github.com/user-attachments/assets/eba12ca7-395e-4348-89b4-1480e1e0a934

### App Type

Electron / App

### Version

v0.0.1-alpha.9

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-09-05 22:29
Duplicate of #268

**Closed** 2024-09-05 22:31 UTC
