### ISSUE TITLE
Add Action filter field: Shortcuts

### ISSUE THREAD

**Issue by PACHAKUTlQ** [RSSNext/Follow#1351] opened 2024-11-03 09:05 UTC
### Clear and concise description of the problem

In Actions->Custom filters->Field, there are only five options: View, Title, Category, Site URL and Feed URL. These options are all general rules without enough flexibility. Would be better if action filters allow manual trigger like shortcuts.

Examples:
1. Someone usually doesn't want AI summary, but sometimes the articles are too long. He wants AI summary only for that article.
2. Someone usually doesn't need translation, but sometimes he cannot understand a word so decided to translate that page.

The current filters cannot cover these cases, where the actions should be _manually triggered_ instead of using filters.

### Suggested solution

Add an option of shortcuts in triggering Actions.
For example, allow users to set the shortcut `Ctrl+T` or whatever to trigger the action of translating the page.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment] 2024-11-05 03:33
Duplicate of #343

**Closed by hyoban** 2024-11-05 03:33 UTC
Labels: enhancement
