### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by 1905634** [RSSNext/Follow#1774] opened 2024-11-24 03:26 UTC
### Error

Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### Stack

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5077:107)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5087:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5074:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5121:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5074:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5074:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5121:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5104:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
    at Zj (https://app.follow.is/vendor/0-EeJr3raE.js:5087:7)
    at Yj (https://app.follow.is/vendor/0-EeJr3raE.js:5061:35)
```

### Environment

**App Version**: 0.2.4-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `XUGDlm_zsee82o6v3ew48`

### Sentry Trace ID
x4kDvXzuVkBRc0-Q1TwlM

**Comment by TonyRL** [comment] 2024-11-24 07:54
Duplicate of #1770

**Closed** 2024-11-25 07:45 UTC
