### ISSUE TITLE
[i18n]: error:key 'general.proxy(zh-CN)' return an object instead of string in networking setting 

### ISSUE THREAD

**Issue by qdriven** [RSSNext/Follow#634] opened 2024-09-25 14:26 UTC
### Type of i18n contribution

New language support

### Language

Chinese

### Description

general.proxy(zh-CN): should be 通用代理
screenshot:
![image](https://github.com/user-attachments/assets/f41a64e3-7ea8-43e0-8472-ab5601b7ec60)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hyoban** [comment] 2024-09-25 14:53
Duplicate of #605

**Closed by hyoban** 2024-09-25 14:53 UTC
Labels: i18n
