### ISSUE TITLE
Add chronological (oldest to newest) sorting option for content feeds

### ISSUE THREAD

**Issue by forkmax** [RSSNext/Follow#1105] opened 2024-10-24 06:18 UTC
## Description
Currently, Follow displays content in reverse chronological order (newest to oldest) across all feed types including articles, Twitter posts, and Weibo posts. While this is common for social media platforms, it can sometimes disrupt the natural reading flow, especially in the following scenarios:

**Current Issues:**
- When reading Twitter threads, we often see replies before the original post, making it difficult to understand the context
- For article series or sequential content, newer posts appear first, forcing readers to scroll down to find the beginning
- Following story developments or news updates becomes challenging as we need to read backwards

**Feature Request:**
I suggest adding a sorting toggle button that allows users to switch between:
- Newest to oldest (current default)
- Oldest to newest (chronological)

**Benefits:**
- Improved reading experience for sequential content
- Better context understanding for Twitter conversations
- More natural content consumption flow
- Enhanced user control over content organization

### Suggested solution

**Suggested Implementation:**
A simple toggle button in the feed view that:
- Persists user preference per feed type
- Can be set globally or per subscription
- Maintains the current default (newest first) while giving users the option to switch

This feature would significantly enhance the reading experience on Follow, especially for users who prefer to consume content in its natural chronological progression.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by geekhuashan** [comment] 2024-10-28 06:01
同需求

**Comment by TonyRL** [comment] 2024-10-28 13:46
Duplicate of #425

**Comment by hyoban** [comment] 2024-10-28 14:38
Thank you very much for your suggestion, let us track this issue there

**Closed by hyoban** 2024-10-28 14:38 UTC
Labels: enhancement

**Comment by geekhuashan** [comment] 2025-03-14 07:20
这个功能需求真的很普遍啊，为什么就是不加呢，not planned，等了这么久，应该也不难吧。
