### ISSUE TITLE
A Query page Bug

### ISSUE THREAD

**Issue by cujiua** [RSSNext/Follow#1265] opened 2024-10-31 11:43 UTC
### Describe the bug

![image](https://github.com/user-attachments/assets/79d1337b-1035-4dd2-a5cc-16822c385687)

### Feed Info

Query page

### App Type

Electron / App

### Version

 0.1.1-beta.1 

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-10-31 14:36
Duplicate of #1264

**Closed** 2024-11-02 04:13 UTC
