### ISSUE TITLE
cannot loggin in fedora

### ISSUE THREAD

**Issue by rain2307** [RSSNext/Follow#1769] opened 2024-11-24 02:30 UTC
### Describe the bug

我用appimage打开后，需要跳转到浏览器登陆，但是浏览器jump不回来，应该是因为没有绑定处理程序把？
fedora弹出一个框，让我选 处理程序，结果也不能制定路径。。

### Feed Info

..

### Reproduction Video

我尝试截图、录制，但是系统崩了

### Environment

```
      a8888b.           Host        -  fedora                                                 
       d888888b.          Machine     -  AZW SER8 V10                                               
       8P"YP"Y88          Kernel      -  6.11.8-300.fc41.x86_64                                     
       8|o||o|88          Distro      -  Fedora Linux 41 (KDE Plasma)                               
       8'    .88          DE          -  KDE                                                        
       8`._.' Y8.         WM          -  kwin_wayland_wr (Wayland)                                  
      d/      `8b.        Packages    -  2344 (rpm), 18 (cargo), 6 (flatpak), 0 (snap), 0 (Homebrew)
     dP        Y8b.       Shell       -  zsh                                                        
    d8:       ::88b.      Terminal    -  konsole                                                    
   d8"         'Y88b      Resolution  -  3840x2160                                                  
  :8P           :888      Uptime      -  4h 12m                                                     
   8a.         _a88P      CPU         -  AMD Ryzen 7 8845HS w/ Radeon 780M Graphics (16)            
 ._/"Yaa     .| 88P|      CPU Load    -  4%                                                         
 \    YP"    `|     `.    Memory      -  9.2 GB / 28.5 GB                                           
 /     \.___.d|    .'     GPU         -  Phoenix3                                                   
 `--..__)     `._.'             
```

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-11-24 07:55
Duplicate of #579

**Closed** 2024-11-25 07:46 UTC
