### ISSUE TITLE
There is a problem with the theme settings in the appearance options in the settings

### ISSUE THREAD

**Issue by hunterle** [RSSNext/Follow#1194] opened 2024-10-28 03:07 UTC
### Describe the bug

外观设置中主题设置成亮色或者深色都不会改变app整体主题颜色，只能改变文章中字体颜色。app颜色只能跟随系统主题颜色切换。

### Feed Info

![微信截图_20241028110555](https://github.com/user-attachments/assets/4dd9e7a9-4377-41b8-a544-791af65ac91c)
![微信截图_20241028110540](https://github.com/user-attachments/assets/ae348a49-7e9f-45f7-82f5-681949141307)
![微信截图_20241028110528](https://github.com/user-attachments/assets/704e2e95-db5a-4bb5-b2f5-399ee0a415f2)
![微信截图_20241028110453](https://github.com/user-attachments/assets/37fba6dd-c947-4eb0-b448-82db1694cfbb)

### App Type

Electron / App

### Version

0.1.1-beta.1

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-28 03:31
Duplicate of #1160. Fixed in https://github.com/RSSNext/Follow/pull/1157.

**Closed by hyoban** 2024-10-28 03:31 UTC
