### ISSUE TITLE
Error in fetching feed: rsshub://bilibili/user/dynamic/3546738654709902

### ISSUE THREAD

**Issue by wanghuasheng** [RSSNext/Follow#1380] opened 2024-11-04 07:27 UTC
### Info:

Feed URL:
```
rsshub://bilibili/user/dynamic/3546738654709902
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/bilibili/user/dynamic/3546738654709902?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.0-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.0-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment] 2024-11-04 07:59
Duplicate of #1381, should be OK now

**Closed by hyoban** 2024-11-04 07:59 UTC
