### ISSUE TITLE
The content is not displaying properly

### ISSUE THREAD

**Issue by GO-PIO** [RSSNext/Follow#562] opened 2024-09-22 08:44 UTC
### Describe the bug

![explorer_QZEYo5ascF](https://github.com/user-attachments/assets/e75a93f4-35b1-43d2-a222-b47174251934)

### Feed Info

https://www.52pojie.cn/forum.php?mod=guide&view=tech&rss=1

### App Type

Electron / App

### Version

v0.0.1-alpha.14

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-09-22 16:16
Duplicate of #290

**Closed by hyoban** 2024-09-22 16:16 UTC
