### ISSUE TITLE
Automatically mark as read after moving the mouse to the article title

### ISSUE THREAD

**Issue by leiyi2000** [RSSNext/Follow#952] opened 2024-10-15 07:04 UTC
### Describe the bug

鼠标移动到部分文章标题后自动标记已读

### Feed Info

rsshub://zhihu/hot/total

### Reproduction Video

https://github.com/user-attachments/assets/94f137f3-7fff-475b-990e-4d639e05df0e

### App Type

Electron / App

### Version

0.0.1-nightly20241011

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-10-15 22:19
Duplicate of #380

**Comment by hyoban** [comment] 2024-10-16 00:36
Please check whether the mark as read on hovering is turned on in the settings item. Please feel free to open this issue again if you still have questions.

**Closed by hyoban** 2024-10-16 00:36 UTC
