### ISSUE TITLE
ruanyifeng, can not be updated on Friday

### ISSUE THREAD

**Issue by HuanBaby1314** [RSSNext/Follow#1701] opened 2024-11-22 02:14 UTC
### Describe the bug

The delay is too long, and you cannot get the latest subscription content even if you refresh it actively.The subscription link below will be updated every Friday.
link: http://feeds.feedburner.com/ruanyifeng
![Image](https://github.com/user-attachments/assets/1a2df005-6f67-4c16-bda2-d23007641e3f)
![Image](https://github.com/user-attachments/assets/1c5b31e3-f450-4e89-a40f-7ad68457235c)

### Feed Info

huanxingan1314@gmail.com

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `GPtl6Toh1MXYf53apsg7B`

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-11-22 05:33
You can try to unsubscribe and then resubscribe

Duplicate of #1679

**Closed by hyoban** 2024-11-22 05:33 UTC
