### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by DDG-ALT** [RSSNext/Follow#1331] opened 2024-11-02 15:04 UTC
### Error

Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### Stack

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ja (https://app.follow.is/vendor/0-KGA-48pw.js:32:25974)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27253)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27709)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27709)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27709)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:30436)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27514)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27514)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27514)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27709)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:30436)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27514)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27514)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27709)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:30436)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27709)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:30436)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27514)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27514)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27709)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27514)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27514)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:30436)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27647)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27514)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
    at Ua (https://app.follow.is/vendor/0-KGA-48pw.js:32:27514)
    at Pe (https://app.follow.is/vendor/0-KGA-48pw.js:32:27401)
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
**Env**: web
**Browser**: Microsoft Edge

**Comment by hyoban** [comment] 2024-11-04 09:34
Can you provide more information on how to reproduce this issue?

**Comment by hyoban** [comment] 2024-11-04 12:57
Looks like this is a duplicate of https://github.com/RSSNext/Follow/issues/1294#issuecomment-2453707546

Duplicate of #1294

**Closed by hyoban** 2024-11-04 12:57 UTC
