### ISSUE TITLE
Will you adapt it to the mobile app?

### ISSUE THREAD

**Issue by lzh-zone** [RSSNext/follow#1060] opened 2024-10-22 12:53 UTC
### Clear and concise description of the problem

请问会做手机端app的适配吗，在手机或者平板上打开显示不支持，请问官方大大能做手机端的适配吗

### Suggested solution

希望能实现手机和平板app上使用

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment] 2024-10-22 13:10
Duplicate of #972

**Closed as not planned** 2024-10-22 13:27 UTC
Labels: enhancement
