### ISSUE TITLE
Error in fetching feed

### ISSUE THREAD

**Issue by Ellioben** [RSSNext/Follow#1937] opened 2024-11-29 16:54 UTC
### Info:

Feed URL:
```
https://rsshub.app/twitter/user/yamato812536
```

Error:
```
Feed fetch error: [GET] "http://10.1.32.41/twitter/user/yamato812536?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `Bb3IfHgp2WYfWSr8iASBU`

**Comment by hyoban** [comment] 2024-11-29 17:15
Duplicate of https://github.com/RSSNext/Follow/discussions/1713

**Closed by hyoban** 2024-11-29 17:15 UTC
