### ISSUE TITLE
Error in fetching feed: https://navi.cnki.net/knavi/rss/XNZY?pcode=CJFD,CCJD

### ISSUE THREAD

**Issue by daytime001** [RSSNext/Follow#1570] opened 2024-11-12 03:05 UTC
### Info:

Feed URL:
```
https://navi.cnki.net/knavi/rss/XNZY?pcode=CJFD,CCJD
```

Error:
```
Feed 获取错误: [GET] "https://navi.cnki.net/knavi/rss/XNZY?pcode=CJFD,CCJD": <no response> fetch failed
```

### Environment

**App Version**: 0.2.0-beta.2
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.2 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `BjAoJjulb53Kg3Tdk5Kgb`

**Comment by TonyRL** [comment] 2024-11-12 03:10
Duplicate of #1309

**Closed** 2024-11-12 03:14 UTC
