### ISSUE TITLE
Error in fetching feed: rsshub://xiaohongshu/user/54b65a70b4c4d66726a976d3/notes

### ISSUE THREAD

**Issue by pinotao** [RSSNext/Follow#1691] opened 2024-11-21 12:49 UTC
### Info:

Feed URL:
```
rsshub://xiaohongshu/user/54b65a70b4c4d66726a976d3/notes
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/xiaohongshu/user/54b65a70b4c4d66726a976d3/notes?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `yfMgAQGUZIa8TMDDdNsfG`

**Comment by yzy1228682367** [comment] 2024-11-22 02:18
It seems that all the subscription sources of Xiaohongshu are invalid.

**Comment by hyoban** [comment] 2024-11-22 05:32
Duplicate of #1662

**Closed by hyoban** 2024-11-22 05:32 UTC
