### ISSUE TITLE
Error in fetching feed: rsshub://xiaohongshu/user/6071c835000000000100b8e8/notes

### ISSUE THREAD

**Issue by rookie-yxp** [RSSNext/Follow#1709] opened 2024-11-22 09:50 UTC
### Info:

Feed URL:
```
rsshub://xiaohongshu/user/6071c835000000000100b8e8/notes
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/xiaohongshu/user/6071c835000000000100b8e8/notes?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `_rVlEBxPQVz3bKL7y3lVm`

**Comment by hyoban** [comment] 2024-11-22 09:53
Duplicate of #1662

**Closed by hyoban** 2024-11-22 09:53 UTC
