### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by JuanDavalos192** [RSSNext/Follow#2337] opened 2024-12-26 17:41 UTC
### Describe the bug

Stuck on the pop-up login interface and cannot move forward in the latest application named "Follow-0.2.8-beta.0-linux-x64.AppImage". Clicking on the icons of all login does not respond normally.![Image](https://github.com/user-attachments/assets/e65f14f0-c62f-4964-bc0e-a8785d1c43cd)

### Feed Info

No correlation

### Environment

The latest AlmarLinux 9 gnome. 

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-12-26 18:10
Duplicate of #579

**Closed** 2024-12-26 19:17 UTC
