### ISSUE TITLE
Error in fetching list: 89506428053044224

### ISSUE THREAD

**Issue by smallyear** [RSSNext/Follow#2102] opened 2024-12-11 03:41 UTC
### Info:

List ID:
```
89506428053044224
```

Error:
```
Cannot add property 89506428053044224, object is not extensible
```

### Environment

**App Version**: 0.2.6-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.6-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `0GQyqMgFLUEvGu0bxJA2P`

**Comment by hyoban** [comment] 2024-12-11 07:47
Duplicate of #1399, Please try rebuilding your database.

**Closed by hyoban** 2024-12-11 07:47 UTC
