### ISSUE TITLE
Can't login in Linux

### ISSUE THREAD

**Issue by catwinee** [RSSNext/follow#1165] opened 2024-10-26 15:11 UTC
### Describe the bug

I am having trouble logging into the Linux AppImage.
I downloaded the AppImage from the release version v0.1.1-beta.0.

Then I run it with "Follow-0.1.1-beta.0-linux-x64.AppImage --enable-features=UseOzonePlatform --ozone-platform=wayland "(since I'm using wayland)
It ran successfully.

![image](https://github.com/user-attachments/assets/7fc2f406-0804-480c-9f20-f3c8912cf2f7)

Next, I logged in using the browser. I was able to pass authentication, and the webapp worked fine. However, my Linux app is still stuck on the login page.
![image](https://github.com/user-attachments/assets/a30e1b9b-9078-4f37-ab4e-4a3d01452547)

Here is part of the terminal output:

...
Request failed : fetch failed
Retrying in 0 seconds
Request failed : fetch failed
Retrying in 5 seconds
Request failed : fetch failed
Retrying in 10 seconds
Request failed : fetch failed
Retrying in 15 seconds
22:49:08.309 (main) › PushReceiver error: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retry$3 (file:///tmp/.mount_FollowQJrNSX/resources/app.asar/dist/main/index.js:10157:12)
    at async checkIn (file:///tmp/.mount_FollowQJrNSX/resources/app.asar/dist/main/index.js:14967:23)
    at async gcm.default (file:///tmp/.mount_FollowQJrNSX/resources/app.asar/dist/main/index.js:14962:19)
    at async PushReceiver2.registerIfNeeded (file:///tmp/.mount_FollowQJrNSX/resources/app.asar/dist/main/index.js:16183:18)
    at async PushReceiver2.connect (file:///tmp/.mount_FollowQJrNSX/resources/app.asar/dist/main/index.js:16123:5)
    at async registerPushNotifications (file:///tmp/.mount_FollowQJrNSX/resources/app.asar/dist/main/index.js:95862:5)
22:49:08.309 (main) › PushReceiver connected

### Feed Info

Not problem for feed.

### Reproduction Video

https://github.com/user-attachments/assets/c8153105-5c48-4b6e-93fc-6c244b12a19c

### App Type

Electron / App

### Version

 v0.1.1-beta.0

### Operating System

Linux

### Browser Info

Firefox

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by code4lala** [comment] 2024-10-27 00:45
> [FOL-606 Can't login in Linux](https://linear.app/follow-app/issue/FOL-606/cant-login-in-linux)

No permission
![image](https://github.com/user-attachments/assets/67fc91ea-beae-48f7-a04f-d9c4bafee4a5)

**Comment by DIYgod** [comment] 2024-10-29 09:34
Duplicate of #579

**Closed as not planned by DIYgod** 2024-10-29 09:34 UTC
