### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'iconClassName')

### ISSUE THREAD

**Issue by amyliu840** [RSSNext/Follow#2222] opened 2024-12-18 17:16 UTC
### Error

Cannot read properties of undefined (reading 'iconClassName')

### Stack

```
TypeError: Cannot read properties of undefined (reading 'iconClassName')

```

### Environment

**App Version**: 0.2.6-beta.0
**OS**: macOS
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment] 2024-12-18 17:48
Duplicate of #2180

**Closed** 2024-12-19 07:11 UTC
