### ISSUE TITLE
生成邀请码时power被吞 When the invitation code is generated, the power is swallowed

### ISSUE THREAD

**Issue by rong6** [RSSNext/Follow#976] opened 2024-10-16 05:59 UTC
### Describe the bug

如图，这是我现在的余额（60）和所有交易记录（共计160）：

![image](https://github.com/user-attachments/assets/197b20a1-925f-4b3c-9005-25bbf48268e3)

当我在邀请界面生成邀请码的时候，邀请码并没有生成，但是余额被扣了100，活生生把我power给吞了：

![image](https://github.com/user-attachments/assets/b3753f4a-2efa-4810-bb8a-628869154e26)

**在交易记录中未显示该项扣款。**，与 #971 情况相同。

### Feed Info

Nothing to do with subscription information.

### App Type

Web

### Operating System

Windows 10

### Browser Info

Microsoft Edge 129.0.2792.89 

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-10-16 06:12
Duplicate of #971

**Comment by DIYgod** [comment] 2024-10-16 06:28
Please DM me on Discord for compensation if it has already been deducted. The new transaction has hotfixed this issue. If it still occurs after this message, please let me know.

**Closed by DIYgod** 2024-10-16 06:28 UTC
