### ISSUE TITLE
Error in fetching feed: rsshub://twitter/media/tmiyatake1

### ISSUE THREAD

**Issue by daichiumamichi** [RSSNext/Follow#1658] opened 2024-11-19 03:14 UTC
### Info:

Feed URL:
```
rsshub://twitter/media/tmiyatake1
```

Error:
```
フィードの取得エラー: [GET] "http://10.1.32.41/twitter/media/tmiyatake1?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `KNVThtPdkWRAaPVhRZbcw`

**Comment by hyoban** [comment] 2024-11-19 03:16
Duplicate of #740

**Closed by hyoban** 2024-11-19 03:16 UTC
