### ISSUE TITLE
Nightly 0.1.1-nightly.20241025 版本，下载安装替换0.1.0版本之后出现bug

### ISSUE THREAD

**Issue by Keturah-i** [RSSNext/Follow#1162] opened 2024-10-26 09:44 UTC
### Describe the bug

安装之后第一次打开出现，关闭软件后重新打开继续复现

dayjs.duration is not function

Follow has a temporary problem,click the below to try reloading the app or another solution?

点击 Retry  无反应，点击 reload，页面刷新，继续出现bug页面

### Feed Info

个人资料名称：Keturah

唯一标识 在第一次安装时，填写了Keturah，但是后续再设置里面查看  是 空 值

### App Type

Electron / App

### Version

0.1.1

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-26 09:52
Duplicate of #1153

**Closed by hyoban** 2024-10-26 09:52 UTC
