### ISSUE TITLE
[Feature Request] Support modifying RSSHub instances in settings

### ISSUE THREAD

**Issue by missuo** [RSSNext/Follow#813] opened 2024-10-08 23:44 UTC
### Clear and concise description of the problem

Currently most RSS relies on RSSHub, for example, Twitter's crawling relies entirely on RSSHub, but because RSSHub needs to carry a large number of user requests, there are cases where it cannot be crawled in the process of using it and the frequency of crawling is not too high. 

There is currently no place to switch RSSHub instances, and it seems that this can only be achieved by manually re-adding them.

### Suggested solution

I hope that custom RSSHub instances can be set in the settings. Considering that the routes of RSSHub are the same, all subscriptions should be able to be re-crawled using the new instance without the need to manually re-add them.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment] 2024-10-29 06:54
Duplicate of #363

**Closed by DIYgod** 2024-10-29 06:54 UTC
Labels: enhancement
