### ISSUE TITLE
加载语言包失败

### ISSUE THREAD

**Issue by edward-kyle** [RSSNext/Follow#507] opened 2024-09-19 09:18 UTC
### Describe the bug

切换语言失败，我看到discord上也有人提到过类似的问题。

### Feed Info

与这个无关

### Reproduction Video

![follow bug](https://github.com/user-attachments/assets/6d442f34-2a23-4da2-8ae6-fa59550c46ed)

### App Type

Electron / App

### Version

v0.0.1-alpha13

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-09-19 09:22
Duplicate of #447

**Closed by hyoban** 2024-09-19 09:22 UTC
