### ISSUE TITLE
Error in fetching feed: rsshub://youtube/playlist/%40Indicators_STR

### ISSUE THREAD

**Issue by Loveworld3033** [RSSNext/Follow#1397] opened 2024-11-05 01:44 UTC
### Info:

Feed URL:
```
rsshub://youtube/playlist/%40Indicators_STR
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/youtube/playlist/%40Indicators_STR?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.1-beta.1
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.1-beta.1 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment] 2024-11-05 01:54
Duplicate of #1393

**Comment by TonyRL** [comment] 2024-11-05 01:55
Please have a look at https://github.com/RSSNext/Follow/issues/1393#issuecomment-2454886344

**Closed** 2024-11-05 02:32 UTC
