### ISSUE TITLE
Error in fetching RSS :https://www.xigua543.com/map/rss.xml

### ISSUE THREAD

**Issue by ACANX** [RSSNext/Follow#1966] opened 2024-12-01 19:33 UTC
Error in fetching RSS :https://www.xigua543.com/map/rss.xml

Feed URL:
```
https://www.xigua543.com/map/rss.xml
```

Error:
```
Feed 获取错误: [GET] "https://www.xigua543.com/map/rss.xml": 403 Forbidden
```

### Environment

**App Version**: 0.2.5-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `XDVAhk_TwLm35LKTg-DFF`

_Originally posted by @ACANX in https://github.com/RSSNext/Follow/discussions/1965_

**Comment by hyoban** [comment] 2024-12-02 01:09
Duplicate of https://github.com/RSSNext/Follow/discussions/1965

**Closed by hyoban** 2024-12-02 01:09 UTC
