### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'image')

### ISSUE THREAD

**Issue by ahao-debug** [RSSNext/Follow#1805] opened 2024-11-25 05:23 UTC
### Error

Cannot read properties of undefined (reading 'image')

### Stack

```
TypeError: Cannot read properties of undefined (reading 'image')
    at SubscriptionItems (https://app.follow.is/assets/user-profile-modal-B-c4PSMe.js:63:96)
    at Nh (https://app.follow.is/vendor/0-EeJr3raE.js:3399:7)
    at Vk (https://app.follow.is/vendor/0-EeJr3raE.js:6342:11)
    at Uk (https://app.follow.is/vendor/0-EeJr3raE.js:6036:11)
    at Tk (https://app.follow.is/vendor/0-EeJr3raE.js:6030:26)
    at Ik (https://app.follow.is/vendor/0-EeJr3raE.js:6015:7)
    at Nk (https://app.follow.is/vendor/0-EeJr3raE.js:5746:7)
    at Ek (https://app.follow.is/vendor/0-EeJr3raE.js:5800:28)
    at jg (https://app.follow.is/vendor/0-EeJr3raE.js:2708:15)
    at https://app.follow.is/vendor/0-EeJr3raE.js:5628:26
```

### Environment

**App Version**: 0.2.4-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `ZLC3kvm1Wlemxp6sB6LxE`

### Sentry Trace ID
wjxVoukfB7d6T2UVZnmV0

**Comment by hyoban** [comment] 2024-11-25 08:32
Duplicate of #1785

**Closed by hyoban** 2024-11-25 08:32 UTC
