### ISSUE TITLE
Bulk Management of Imported RSS Feeds

### ISSUE THREAD

**Issue by Chikedor** [RSSNext/Follow#458] opened 2024-09-17 12:27 UTC
### Clear and concise description of the problem

As a user who has imported a large number of RSS feeds, I'm facing a significant inconvenience. Currently, Follow requires managing each imported feed individually, which is extremely time-consuming and inefficient, especially when dealing with numerous outdated or non-functional feeds marked as "Importing". This one-by-one approach is frustrating and impractical for users with extensive feed lists.

### Suggested solution

Implement a bulk management system with checkboxes next to each feed in the left column. This would allow:

1. Selecting multiple feeds simultaneously.
2. Performing batch actions like deleting or moving to folders.
3. Adding a dropdown menu for actions like "Delete selected", "Move to folder", etc.
4. This solution would dramatically reduce the time and effort required to organize and clean up imported feeds, turning a potentially hours-long task into a quick and efficient process.

### Alternative

Introduce a "bulk edit" mode activated by a button, enabling temporary multi-selection of feeds.

### Additional context

The current feed-by-feed management is a major bottleneck in the user experience, especially after importing from long-standing RSS collections. This feature would significantly enhance user satisfaction and productivity when setting up or maintaining their Follow account.

![image](https://github.com/user-attachments/assets/398dbc5c-cd19-4f6a-ac71-56f66d5e7b70)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment] 2024-09-24 06:17
Duplicate of #272.

**Closed** 2024-09-24 08:04 UTC
Labels: enhancement
