### ISSUE TITLE
Error in fetching feed: rsshub://twitter/user/%40amane_bushi

### ISSUE THREAD

**Issue by kakuuuuu** [RSSNext/Follow#1649] opened 2024-11-18 11:29 UTC
### Info:

Feed URL:
```
rsshub://twitter/user/%40amane_bushi
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/%40amane_bushi?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `q8TSai0oc7nlnJgH2HW7c`

**Comment by hyoban** [comment] 2024-11-18 11:30
Duplicate of #740

**Closed by hyoban** 2024-11-18 11:30 UTC
