### ISSUE TITLE
Unable to add some telegram channels

### ISSUE THREAD

**Issue by oligarchpoly** [RSSNext/Follow#622] opened 2024-09-25 03:49 UTC
### Describe the bug

There were some telegram channels that was not able to be added to the feeds. This was a channel that belonged to me but i wasnt able to add it and hence unable to claim it

https://t.me/threadingontheedge

### Feed Info

https://t.me/threadingontheedge

### App Type

Electron / App

### Version

0.0.1-alpha.17

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-09-25 03:55
Duplicate of #603

**Closed** 2024-09-25 05:07 UTC
