### ISSUE TITLE
The amount of power minted is wrong

### ISSUE THREAD

**Issue by OuyangMu** [RSSNext/Follow#1122] opened 2024-10-25 01:31 UTC
### Describe the bug

![image](https://github.com/user-attachments/assets/86f5f561-bcf4-4b3f-bfe4-29eb2fb350c8)
或许是每日铸造的数量显示错误，是20个而不是25。又或许是power余额错误。

### Feed Info

null

### App Type

Electron / App

### Version

0.0.1-alpha.22

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-10-25 01:33
Duplicate of #1116

> Starting now, a universal tax will be applied to activities and transactions happening on Follow.

https://x.com/follow_app_/status/1849346647438017015

**Closed by hyoban** 2024-10-25 01:33 UTC
