### ISSUE TITLE
always show ‘App is upgraded...’ when open

### ISSUE THREAD

**Issue by loongzhu** [RSSNext/Follow#1498] opened 2024-11-08 07:26 UTC
### Environment

**App Version**: 0.1.2-nightly.20241106
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-nightly.20241106 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `5xXX49vGVr53zDlHUjN3R`

![Image](https://github.com/user-attachments/assets/f23545fa-cfcf-4252-8c95-4c98156f52dc)

**Comment by hyoban** [comment] 2024-11-08 08:23
Check your app version from the local storage

![Image](https://github.com/user-attachments/assets/c47abec7-402f-4313-9e8b-a51db63b9179)

**Comment by hyoban** [comment] 2024-11-08 08:31
Duplicate of #1456

**Closed by hyoban** 2024-11-08 08:31 UTC
