### ISSUE TITLE
Error in fetching feed: rsshub://xiaohongshu/user/5c5c284f000000001b028804/notes

### ISSUE THREAD

**Issue by caoer312** [RSSNext/Follow#1673] opened 2024-11-19 15:18 UTC
### Info:

Feed URL:
```
rsshub://xiaohongshu/user/5c5c284f000000001b028804/notes
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/xiaohongshu/user/5c5c284f000000001b028804/notes?format=json": 500 Internal Server Error
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `fSoJohDYDRy0d7PvZfqf3`

**Comment by hyoban** [comment] 2024-11-19 15:33
Duplicate of #1662

**Closed by hyoban** 2024-11-19 15:33 UTC
