### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by lihei3858** [RSSNext/Follow#2027] opened 2024-12-06 08:56 UTC
### Error

Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### Stack

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at qa (https://app.follow.is/vendor/0-270N51eK.js:40:26062)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27352)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:30547)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:30547)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:30547)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:30547)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:30547)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27750)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
```

### Environment

**App Version**: 0.2.6-beta.0
**OS**: Linux
**User Agent**: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `iDE1Ep8mMxVBA8QOzfZHJ`

### Sentry Trace ID
ZFoj2kjZ49KElFfHz3SOD

**Comment by TonyRL** [comment] 2024-12-06 15:49
Duplicate of #1770

**Closed** 2024-12-19 07:17 UTC
