### ISSUE TITLE
Error in fetching feed: https://rsshub.app/twitter/user/qinphoto0510

### ISSUE THREAD

**Issue by chpaladin** [RSSNext/Follow#1638] opened 2024-11-17 07:50 UTC
### Info:

Feed URL:
```
https://rsshub.app/twitter/user/qinphoto0510
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/qinphoto0510?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.1-nightly.20241116
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.1-nightly.20241116 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `BjSVd9L9zfTywsliI3veR`

**Comment by hyoban** [comment] 2024-11-18 02:13
Duplicate of #740

**Closed by hyoban** 2024-11-18 02:13 UTC
