### ISSUE TITLE
Error in fetching feed: rsshub://twitter/user/horieyui_staff

### ISSUE THREAD

**Issue by stellarhalo** [RSSNext/Follow#1502] opened 2024-11-08 09:27 UTC
### Info:

Feed URL:
```
rsshub://twitter/user/horieyui_staff
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/horieyui_staff?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

**Comment by hyoban** [comment] 2024-11-08 10:34
Duplicate of #740

**Closed by hyoban** 2024-11-08 10:34 UTC
