### ISSUE TITLE
sidebar supports drag and drop

### ISSUE THREAD

**Issue by asyncguo** [RSSNext/Follow#1193] opened 2024-10-28 03:06 UTC
### Clear and concise description of the problem

Expect the list in the sidebar to be quickly categorized by dragging and dropping list items.

<img width="665" alt="image" src="https://github.com/user-attachments/assets/5f0c417d-2cee-4513-94a8-cc9d21c4b64e">

### Suggested solution

nothing

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment] 2024-10-28 03:38
Duplicate of #272, let's track this issue there

**Closed by hyoban** 2024-10-28 03:38 UTC
Labels: enhancement
