### ISSUE TITLE
Unable to log in through a browser

### ISSUE THREAD

**Issue by Free-Aaron-Li** [RSSNext/Follow#1702] opened 2024-11-22 02:28 UTC
### Describe the bug

When I log in with the client, I am automatically redirected to the browser to complete the login, but when I complete the login, the client still shows that I have not completed the login.
I've tried using firefox and chrome, but neither worked.

---

I think this should be an issue with the software on Linux, but I tried logging into the account via VSCode and it was no problem. Soon after, I tried to log in to my account via Warp and it worked. Now, I suspect that there is a problem when opening the software via xdg-open.

### Feed Info

communicate_aaron@outlook.com

### Reproduction Video

https://github.com/user-attachments/assets/70b41332-800b-40b9-aed5-6bc6d0e82b6a

### Environment

App Version: 0.2.3-beta.0
OS: Linux 6.6.59-amd64-desktop-hwe
Env: electron
Browser: Firefox

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-11-22 03:17
Duplicate of #579

**Closed** 2024-11-22 05:31 UTC
