### ISSUE TITLE
Error in fetching feed: rsshub://twitter/list/ayuan1000

### ISSUE THREAD

**Issue by Perrysix** [RSSNext/Follow#1383] opened 2024-11-04 09:38 UTC
### Info:

Feed URL:
```
rsshub://twitter/list/ayuan1000
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/list/ayuan1000?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

**Comment by hyoban** [comment] 2024-11-04 09:40
Duplicate of #740

**Closed by hyoban** 2024-11-04 09:40 UTC
