### ISSUE TITLE
小红书rss显示不正常

### ISSUE THREAD

**Issue by dddaniel1** [RSSNext/Follow#875] opened 2024-10-11 04:24 UTC
### Describe the bug

显示消息只显示一条。
![image](https://github.com/user-attachments/assets/86f9a176-b4da-4b91-af24-154bf982deff)

### Feed Info

feedUrl: rsshub://xiaohongshu/user/59299f4b50c4b402f057da23/notes
feedId: 66821239397576704

### App Type

Electron / App

### Version

0.0.1-nightly.20241009 

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment] 2024-10-18 03:43
Duplicate of #756

**Closed** 2024-10-18 03:45 UTC
