### ISSUE TITLE
增加文章列表紧凑化布局，隐藏正文预览

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#779] opened 2024-10-06 02:52 UTC
### Clear and concise description of the problem

建议为文章标题列表增加一个紧凑化布局，减少上下间距，隐藏正文内容只显示标题，使更多文章标题能够同时显示在页面上，提高页面利用率和浏览效率。

效果类似于:
![image](https://github.com/user-attachments/assets/a26fd269-a22d-46eb-93e2-ae0915352a63)

### Suggested solution

- 可以和 设置 → 外观  → 界面字体大小 配合调整使用

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment] 2024-10-08 13:42
Duplicate of #395

**Comment by DIYgod** [comment] 2024-10-29 06:11
I think this this issue has been resolved, if the problem still exists, please feel free to reopen it.

**Closed by DIYgod** 2024-10-29 06:11 UTC
Labels: enhancement

**Comment by EnterMan123** [comment] 2024-10-29 06:43
The requirement is as follows: regardless of whether in dual-column or wide mode, only the title should be displayed **(but the article image should also be included)**.

Sometimes, when we read information, we don’t need too many other factors to distract our attention. Only the title should be retained.

👇
Similar to the desired effect:

![1](https://github.com/user-attachments/assets/3487d4db-19cd-41ad-ae66-72cea1c40b98)
![2](https://github.com/user-attachments/assets/3169055c-8292-4c1f-b7a6-a0eb6012cb6b)


Perhaps there could be a button for 'only title'.

**Comment by DIYgod** [comment] 2024-10-29 06:57
I believe the current approach of using a single-line description meets the needs of most people. I don't want to introduce a similar model that could complicate user perception.

**Comment by EnterMan123** [comment] 2024-10-29 07:06
Well, for an RSS software, providing customization is very important. I understand your position and hope you might reconsider in the future.

**Comment by DIYgod** [comment] 2024-10-29 07:43
Possibly related to #256, we will provide custom CSS function later.
