### ISSUE TITLE
Report a bug In the follow app on the mac side, the secondary content page of the article column cannot be closed.

### ISSUE THREAD

**Issue by stellarhalo** [RSSNext/Follow#1403] opened 2024-11-05 04:05 UTC
### Describe the bug

  mac端 的follow app中文章栏目中的二级内容页无法关闭 同时点击图中红框中的按钮没有反应

### Feed Info

  mac端 的follow app中文章栏目中的二级内容页无法关闭 同时点击图中红框中的按钮没有反应![Image](https://github.com/user-attachments/assets/009abb9f-183d-4b45-8657-336fcb5fd9aa)

### Reproduction Video

https://github.com/user-attachments/assets/15dcde3f-3a8b-428a-912a-5afd796ce396

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment] 2024-11-05 04:11
Duplicate of #1311, and already fixed in https://github.com/RSSNext/Follow/commit/e654c3ac165e5eb276ba51dc4ae0ab2da230a9d1

**Closed by hyoban** 2024-11-05 04:11 UTC
