### ISSUE TITLE
Error in fetching feed: https://rsshub.app/cnki/journals/SXXT

### ISSUE THREAD

**Issue by qkwang98** [RSSNext/Follow#1371] opened 2024-11-04 02:55 UTC
### Info:

Feed URL:
```
https://rsshub.app/cnki/journals/SXXT
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/cnki/journals/SXXT?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-nightly.20241103
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-nightly.20241103 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `iZNTo8DFt2z5WmPEZuJqD`

**Comment by qkwang98** [comment] 2024-11-04 02:56
惠书敬悉，迟复为歉！Thank you. Your email is received and will be handled  as soon as possible.——汪棋凯

**Comment by hyoban** [comment] 2024-11-04 09:26
Duplicate of #733

**Closed by hyoban** 2024-11-04 09:26 UTC
