### ISSUE TITLE
Error in fetching feed: rsshub://youtube/playlist/%40%E9%9B%B6%E5%BA%A6%E8%A7%A3%E8%AF%B4

### ISSUE THREAD

**Issue by BINBHo** [RSSNext/Follow#1435] opened 2024-11-06 08:58 UTC
### Info:

Feed URL:
```
rsshub://youtube/playlist/%40%E9%9B%B6%E5%BA%A6%E8%A7%A3%E8%AF%B4
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/youtube/playlist/%40%E9%9B%B6%E5%BA%A6%E8%A7%A3%E8%AF%B4?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment] 2024-11-06 09:02
Duplicate of #1393

**Comment by TonyRL** [comment] 2024-11-06 09:02
Please have a look at https://github.com/RSSNext/Follow/issues/1393#issuecomment-2454886344

**Closed** 2024-11-06 09:43 UTC
