### ISSUE TITLE
请问邀请码如何获取呢？

### ISSUE THREAD

**Issue by baileichao** [RSSNext/follow#208] opened 2024-08-05 13:49 UTC
### Clear and concise description of the problem

如题。

### Suggested solution

如题。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment] 2024-08-05 15:28
Duplicate of #126

**Closed by TonyRL** 2024-08-05 15:28 UTC
Labels: enhancement

**Comment by fighting12code** [comment] 2024-10-14 02:37
Ask for an invitation code, thank you very much, email :838193609@qq.com
