### ISSUE TITLE
Error in fetching feed: rsshub://twitter/media/yorimoto_s

### ISSUE THREAD

**Issue by yeefai** [RSSNext/Follow#1548] opened 2024-11-10 10:27 UTC
### Info:

Feed URL:
```
rsshub://twitter/media/yorimoto_s
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/media/yorimoto_s?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.0-beta.2
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.2 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `He7QfroEMaAoDCVXOXOr5`

**Comment by TonyRL** [comment] 2024-11-10 10:29
Duplicate of #740

**Closed** 2024-11-11 02:29 UTC
