### ISSUE TITLE
Please add a news viewing option where the full headline is displayed, regardless of its length.

### ISSUE THREAD

**Issue by Sm1tee** [RSSNext/Follow#2384] opened 2024-12-30 16:29 UTC
### Clear and concise description of the problem

Please add a viewing option similar to Feedly, with a large image and a headline. Currently, the closest option is the image view, but the headline gets cut off, and I have to open the news item to understand what it's about, which is inconvenient.

![Image](https://github.com/user-attachments/assets/c8d684d0-0c0a-4578-a364-92f698b44608)

### Suggested solution

Alternatively, please ensure that the news headline is not cut off midway (currently, it is truncated in all viewing modes, even in articles). Or create another viewing option, such as a card-style view.![Image](https://github.com/user-attachments/assets/1a011236-15c3-44f0-8a5d-d87f357351ea)

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by TonyRL** [comment] 2024-12-30 16:36
Duplicate of #1298

**Closed** 2024-12-31 01:18 UTC
Labels: enhancement
