### ISSUE TITLE
Error in fetching feed: rsshub://twitter/user/jerryjliu0

### ISSUE THREAD

**Issue by yellowbig** [RSSNext/Follow#1655] opened 2024-11-19 00:54 UTC
### Info:

Feed URL:
```
rsshub://twitter/user/jerryjliu0
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/user/jerryjliu0?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `8T5mdkclI82hIA-31I0Mx`

**Comment by TonyRL** [comment] 2024-11-19 01:00
Duplicate of #740

**Closed** 2024-11-19 03:09 UTC
