### ISSUE TITLE
Error in fetching list: 68649150114432000

### ISSUE THREAD

**Issue by sl-wen** [RSSNext/Follow#1745] opened 2024-11-23 01:56 UTC
### Info:

List ID:
```
68649150114432000
```

Error:
```
Cannot add property 68649150114432000, object is not extensible
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `i1wdi60AysBlFpC-bFq3u`

**Comment by hyoban** [comment] 2024-11-25 09:00
Duplicate of #1399

**Closed by hyoban** 2024-11-25 09:00 UTC
