### ISSUE TITLE
Feed Error: 夏天心 - 小红书笔记, [GET] "http://10.1.32.41/xiaohongshu/user/59f59b944eacab55eca1d820/notes?format=json": 503 Service Unavailable

### ISSUE THREAD

**Issue by rot-muggles** [RSSNext/Follow#1622] opened 2024-11-16 03:21 UTC
### Error

Error Message: [GET] "http://10.1.32.41/xiaohongshu/user/59f59b944eacab55eca1d820/notes?format=json": 503 Service Unavailable

### Info

```json
{
  "type": "feed",
  "id": "70568852018871296",
  "title": "夏天心 - 小红书笔记",
  "errorAt": "2024-11-15T14:31:17.702Z",
  "errorMessage": "[GET] \"http://10.1.32.41/xiaohongshu/user/59f59b944eacab55eca1d820/notes?format=json\": 503 Service Unavailable",
  "url": "rsshub://xiaohongshu/user/59f59b944eacab55eca1d820/notes",
  "image": "https://sns-avatar-qc.xhscdn.com/avatar/62a2fca12f4e516af0e7d5a5.jpg?imageView2/2/w/540/format/webp",
  "siteUrl": "https://www.xiaohongshu.com/user/profile/59f59b944eacab55eca1d820",
  "ownerUserId": null
}
```

### Environment

**App Version**: 0.2.1-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.1-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `NndmbbQba8JYFU4fG6JmG`

**Comment by hyoban** [comment] 2024-11-21 08:08
Duplicate of #1662

**Closed by hyoban** 2024-11-21 08:08 UTC
